import { LEVELS } from './src/core/levels.ts';
const p = LEVELS[49]!;
const n = p.size;
const cells = p.solutionCells!;
const rc = cells.map((i) => [Math.floor(i / n), i % n]);
console.log('第 50 關 柯基座標 (列,欄):', rc.map(([r, c]) => `${r + 1},${c + 1}`).join('  '));
const byRow: Record<number, number[]> = {};
for (const [r, c] of rc) (byRow[r] ??= []).push(c);
const shared = Object.entries(byRow).filter(([, v]) => v.length > 1);
console.log('同一條複合列上有兩隻的:', shared.map(([r, v]) => `第 ${+r + 1} 列 → 欄 ${v.map((x) => x + 1).join(' 與 ')}`).join('; ') || '（無）');
const byCol: Record<number, number[]> = {};
for (const [r, c] of rc) (byCol[c] ??= []).push(r);
const sharedC = Object.entries(byCol).filter(([, v]) => v.length > 1);
console.log('同一條複合欄上有兩隻的:', sharedC.map(([c, v]) => `第 ${+c + 1} 欄 → 列 ${v.map((x) => x + 1).join(' 與 ')}`).join('; ') || '（無）');
