// 此檔由 scripts/build-levels.ts 自動產生，請勿手動編輯。
// 重新產生：npm run levels
//
// 每一關都經過求解器驗證，確認「恰好一組解」。
//   regions  — 每個字元代表一個彩色區域
//   solution — solution[row] = 該列柯基所在的欄
//   given    — 開局就先擺好、不可更動的柯基

import type { DifficultyId, Puzzle } from './types.ts';

export const LEVELS: Record<DifficultyId, readonly Puzzle[]> = {
  easy: [
    {
      id: 'easy-1',
      size: 6,
      difficulty: 'easy',
      regions: [
      'AAABEE',
      'ACCBBE',
      'ACBBBE',
      'CCBDEE',
      'CFDDEE',
      'CFFFEE',
      ],
      solution: [0, 4, 1, 3, 5, 2],
      given: [[5, 2]],
    },
    {
      id: 'easy-2',
      size: 6,
      difficulty: 'easy',
      regions: [
      'DAAAAB',
      'DDACBB',
      'DDDCCC',
      'DDEEEE',
      'DDEEEF',
      'DDEFFF',
      ],
      solution: [1, 5, 3, 0, 2, 4],
      given: [[1, 5]],
    },
    {
      id: 'easy-3',
      size: 6,
      difficulty: 'easy',
      regions: [
      'CCAAAB',
      'CCCAAB',
      'CCCFDB',
      'CEEFDD',
      'CEEFFD',
      'EEEFFD',
      ],
      solution: [2, 5, 0, 4, 1, 3],
      given: [[1, 5]],
    },
    {
      id: 'easy-4',
      size: 6,
      difficulty: 'easy',
      regions: [
      'BAACCC',
      'BBBCCC',
      'DDDCCC',
      'DDDEEF',
      'DEEEFF',
      'DDFFFF',
      ],
      solution: [2, 0, 4, 1, 3, 5],
      given: [[3, 1]],
    },
    {
      id: 'easy-5',
      size: 6,
      difficulty: 'easy',
      regions: [
      'AAAAAB',
      'AACABB',
      'ACCBBD',
      'CCCCDD',
      'CCEEDD',
      'CFFEEE',
      ],
      solution: [0, 4, 2, 5, 3, 1],
      given: [[2, 2]],
    },
    {
      id: 'easy-6',
      size: 6,
      difficulty: 'easy',
      regions: [
      'BBBAAA',
      'BCAADD',
      'BCCADD',
      'BCCCCD',
      'BEFDDD',
      'EEFFDD',
      ],
      solution: [4, 0, 2, 5, 1, 3],
      given: [[2, 2]],
    },
    {
      id: 'easy-7',
      size: 6,
      difficulty: 'easy',
      regions: [
      'BBBAAC',
      'DBBBCC',
      'DDDECC',
      'DEEECE',
      'FEEEEE',
      'FFEEEE',
      ],
      solution: [4, 2, 5, 0, 3, 1],
      given: [[1, 2]],
    },
    {
      id: 'easy-8',
      size: 6,
      difficulty: 'easy',
      regions: [
      'DDAAAA',
      'DBBCCA',
      'DBCCEA',
      'DDDCEA',
      'FDEEEA',
      'FFFFEE',
      ],
      solution: [5, 1, 3, 0, 4, 2],
      given: [[2, 3]],
    },
    {
      id: 'easy-9',
      size: 6,
      difficulty: 'easy',
      regions: [
      'BBBBAA',
      'DBBCCC',
      'DDDCCC',
      'DDDDCC',
      'FDDFCE',
      'FFFFEE',
      ],
      solution: [4, 1, 3, 0, 5, 2],
      given: [[4, 5]],
    },
    {
      id: 'easy-10',
      size: 6,
      difficulty: 'easy',
      regions: [
      'CCAAAB',
      'CAABBB',
      'CCDDDB',
      'EFFDDB',
      'EFFFDD',
      'FFFDDD',
      ],
      solution: [3, 5, 1, 4, 0, 2],
      given: [[3, 4]],
    },
    {
      id: 'easy-11',
      size: 6,
      difficulty: 'easy',
      regions: [
      'AAAAAB',
      'DAAAAB',
      'DCCCBB',
      'DDCCCE',
      'FDDCEE',
      'FEEEEE',
      ],
      solution: [2, 5, 3, 1, 4, 0],
      given: [[4, 4]],
    },
    {
      id: 'easy-12',
      size: 6,
      difficulty: 'easy',
      regions: [
      'AAAABB',
      'AAAABB',
      'ECCDDB',
      'EDDDFB',
      'EEEFFB',
      'EEFFFB',
      ],
      solution: [2, 5, 1, 3, 0, 4],
      given: [[0, 2]],
    },
  ],
  hard: [
    {
      id: 'hard-1',
      size: 8,
      difficulty: 'hard',
      regions: [
      'CCBBBAAA',
      'CCCCBAGA',
      'CCDDBHGA',
      'CCCDDHGA',
      'EEFFDHGG',
      'FFFFDHHG',
      'FFHHHHHG',
      'FFHHHHHH',
      ],
      solution: [6, 4, 1, 3, 0, 2, 7, 5],
      given: [[2, 1]],
    },
    {
      id: 'hard-2',
      size: 8,
      difficulty: 'hard',
      regions: [
      'BAAAACCC',
      'BBAAACCC',
      'BBAAACCF',
      'DDDEEECF',
      'DDEEEGFF',
      'DDGGGGFF',
      'HDGGGGFF',
      'HGGGGFFF',
      ],
      solution: [3, 1, 6, 2, 4, 7, 5, 0],
      given: [[7, 0]],
    },
    {
      id: 'hard-3',
      size: 8,
      difficulty: 'hard',
      regions: [
      'CCCAAADB',
      'CCEGADDB',
      'CEEGDDDD',
      'CEGGDDFF',
      'EEEGFFFF',
      'EEEGFFFF',
      'GEGGGFFF',
      'GGGHHFFF',
      ],
      solution: [3, 7, 0, 5, 1, 6, 2, 4],
      given: [[6, 2]],
    },
    {
      id: 'hard-4',
      size: 8,
      difficulty: 'hard',
      regions: [
      'AAAACCCC',
      'BAAAACCC',
      'BDDDDEEC',
      'DDFEEEEE',
      'DDFFFEEE',
      'DFFHGGGG',
      'FFHHGGGG',
      'HHHHHGGG',
      ],
      solution: [3, 0, 7, 1, 5, 2, 6, 4],
      given: [[5, 2]],
    },
    {
      id: 'hard-5',
      size: 8,
      difficulty: 'hard',
      regions: [
      'BBBBAAAC',
      'BBEECCCC',
      'EEEEDDCF',
      'EEDDDDDF',
      'GEEEDFFF',
      'GEGGHFHH',
      'GGGHHHHH',
      'GHHHHHHH',
      ],
      solution: [4, 0, 6, 3, 1, 5, 2, 7],
      given: [[3, 3]],
    },
    {
      id: 'hard-6',
      size: 8,
      difficulty: 'hard',
      regions: [
      'BBAAAEEE',
      'CBBBAAEE',
      'CBAAAEEE',
      'CCFDDDEE',
      'FFFFGGEG',
      'FFHHGGGG',
      'FFHHGGGG',
      'FFHHHHHG',
      ],
      solution: [4, 2, 0, 3, 6, 1, 7, 5],
      given: [[1, 2]],
    },
    {
      id: 'hard-7',
      size: 8,
      difficulty: 'hard',
      regions: [
      'BBBDAAAA',
      'BDDDACCE',
      'BDDDDCEE',
      'DDFFEEEE',
      'DFFFHEGE',
      'FFFHHGGG',
      'FHHHHGGG',
      'FHHHHGGG',
      ],
      solution: [4, 0, 5, 1, 7, 2, 6, 3],
      given: [[1, 0]],
    },
    {
      id: 'hard-8',
      size: 8,
      difficulty: 'hard',
      regions: [
      'CCCBBBAA',
      'CCBBBBBB',
      'CCCBBBBB',
      'DCCCBEEE',
      'DCCGBBBE',
      'FFCGGGGE',
      'FCCGGGGE',
      'FHHHHGGE',
      ],
      solution: [6, 4, 2, 0, 7, 1, 5, 3],
      given: [[2, 2]],
    },
    {
      id: 'hard-9',
      size: 8,
      difficulty: 'hard',
      regions: [
      'CBBBBAAA',
      'CBBBBBDD',
      'CBBDBDDD',
      'CDDDDDED',
      'CFDDDDEE',
      'FFFGGEEE',
      'HHGGEEGE',
      'HHGGGGGE',
      ],
      solution: [5, 3, 0, 4, 7, 2, 6, 1],
      given: [[1, 3]],
    },
    {
      id: 'hard-10',
      size: 8,
      difficulty: 'hard',
      regions: [
      'BBDAAAAA',
      'BDDCCCCF',
      'BDDDCEFF',
      'DDGGCEEF',
      'DGGGEEFF',
      'DGGGHFFF',
      'GGGGHHFF',
      'GGGGHHHF',
      ],
      solution: [3, 0, 4, 1, 5, 7, 2, 6],
      given: [[2, 4]],
    },
    {
      id: 'hard-11',
      size: 8,
      difficulty: 'hard',
      regions: [
      'BCCCCAAA',
      'BBCAAADD',
      'BCCCAADD',
      'BBCCEAAD',
      'HFEEEGDD',
      'HFFEEGGD',
      'HFGGGGDD',
      'HGGGGDDD',
      ],
      solution: [6, 1, 3, 7, 4, 2, 5, 0],
      given: [[3, 7]],
    },
    {
      id: 'hard-12',
      size: 8,
      difficulty: 'hard',
      regions: [
      'BBAAAAAA',
      'BBBAAAAA',
      'CBBBBADD',
      'CCBBDADD',
      'EEBFDDDD',
      'EEHFFDDD',
      'EEHFFFFG',
      'EHHHFFGG',
      ],
      solution: [5, 2, 0, 6, 1, 4, 7, 3],
      given: [[4, 1]],
    },
  ],
  expert: [
    {
      id: 'expert-1',
      size: 9,
      difficulty: 'expert',
      regions: [
      'AAACCBBBB',
      'AACCCBEBE',
      'AACCCEEEE',
      'DDCCCEEEE',
      'DCCCCFEGG',
      'DHFFFFEGG',
      'HHFIIIGGI',
      'HFFIIIIII',
      'HFFIIIIII',
      ],
      solution: [2, 5, 3, 1, 6, 4, 7, 0, 8],
      given: [],
    },
    {
      id: 'expert-2',
      size: 9,
      difficulty: 'expert',
      regions: [
      'EAACCBBBB',
      'EEACCCDBB',
      'ECCCCCDDD',
      'EEEFGGIID',
      'EFFFGGIII',
      'FFFGGGGII',
      'FHHHHGIII',
      'HHHHGGIII',
      'HHHHGIIII',
      ],
      solution: [1, 7, 4, 8, 0, 2, 5, 3, 6],
      given: [],
    },
    {
      id: 'expert-3',
      size: 9,
      difficulty: 'expert',
      regions: [
      'BBBBCCCAA',
      'BBBBCDCCA',
      'BBBBBDCFF',
      'BBDDDDCEF',
      'BBDDDEEEF',
      'BBGEEEEEF',
      'BGGGGEEEF',
      'HHHGGGGGF',
      'IIHHGGFFF',
      ],
      solution: [7, 1, 6, 3, 5, 8, 4, 2, 0],
      given: [],
    },
    {
      id: 'expert-4',
      size: 9,
      difficulty: 'expert',
      regions: [
      'BBBDAAACC',
      'BBBDACACC',
      'BBBDACCCC',
      'BBDDACCCC',
      'BBDEEFFCC',
      'BDDDEEFCC',
      'BGDGGGFFF',
      'HGGGGGFFF',
      'HHGGGGIIF',
      ],
      solution: [5, 1, 8, 2, 4, 6, 3, 0, 7],
      given: [],
    },
    {
      id: 'expert-5',
      size: 9,
      difficulty: 'expert',
      regions: [
      'DAAAAABBB',
      'DDDDEEBBC',
      'DDDEEECCC',
      'FDEEEEGGG',
      'FFFFEEEGG',
      'FFFEEHGGG',
      'FIFHHHGGG',
      'FIHHGGGHG',
      'IIHHHHHHG',
      ],
      solution: [4, 6, 8, 1, 5, 2, 7, 3, 0],
      given: [],
    },
    {
      id: 'expert-6',
      size: 9,
      difficulty: 'expert',
      regions: [
      'EEBBBBAAA',
      'EEBBBBACD',
      'EEBBBBCCD',
      'EEFGBBDDD',
      'EEFGGGGII',
      'HHFGGGGGI',
      'HHHGGIGGI',
      'HHHIIIGII',
      'HHHIIIIII',
      ],
      solution: [7, 3, 6, 8, 0, 2, 4, 1, 5],
      given: [],
    },
    {
      id: 'expert-7',
      size: 9,
      difficulty: 'expert',
      regions: [
      'AAAAAAAAC',
      'BDDAEECCC',
      'BDAAEEEHC',
      'DDEEEEEHH',
      'DEEFEFHHH',
      'DEFFFFFHH',
      'DGFGGIFFH',
      'GGGGIIHHH',
      'GGGIIIIIH',
      ],
      solution: [2, 0, 8, 1, 4, 6, 3, 7, 5],
      given: [],
    },
    {
      id: 'expert-8',
      size: 9,
      difficulty: 'expert',
      regions: [
      'CAAABBBEE',
      'CCCBBBEEE',
      'CCCDDBBBE',
      'CCFFDBEEE',
      'CCFFDGGEE',
      'CCFFGGGEE',
      'CCFFGGGEG',
      'CCHFIGGGG',
      'HHHHIIIGG',
      ],
      solution: [1, 5, 0, 4, 7, 3, 8, 2, 6],
      given: [],
    },
    {
      id: 'expert-9',
      size: 9,
      difficulty: 'expert',
      regions: [
      'GGBBBCCAA',
      'GGDBBCCCC',
      'GGDBCCEEE',
      'GGDCCEEEE',
      'GGFFEEHHE',
      'GGGFFEHEE',
      'GIIFHHHHH',
      'IIIHHHHHH',
      'IIIHHHHHH',
      ],
      solution: [7, 3, 5, 2, 8, 4, 0, 6, 1],
      given: [],
    },
    {
      id: 'expert-10',
      size: 9,
      difficulty: 'expert',
      regions: [
      'CCBBBBBAA',
      'CCBBDBBBG',
      'CDDDDDFGG',
      'EDDDFDFFG',
      'EEEEFFFGG',
      'EHEEHFFGI',
      'EHHHHIIGI',
      'EHHHHIIII',
      'HHHHHIIII',
      ],
      solution: [8, 2, 0, 3, 1, 5, 7, 4, 6],
      given: [],
    },
    {
      id: 'expert-11',
      size: 9,
      difficulty: 'expert',
      regions: [
      'CCCAAAAAA',
      'CCCCBBBAA',
      'CCCCBAAAA',
      'CCBBBBDAD',
      'ECBGBBDDD',
      'EEEGFFFFF',
      'EEGGIIIFF',
      'EGGHHIIFF',
      'EEEEEIIFF',
      ],
      solution: [3, 5, 1, 8, 0, 7, 2, 4, 6],
      given: [],
    },
    {
      id: 'expert-12',
      size: 9,
      difficulty: 'expert',
      regions: [
      'AAAAAAABB',
      'AAAABBBBB',
      'AACCCBBDD',
      'ECCCCDBBD',
      'ECECCDDDD',
      'EEEFFDDDI',
      'GFFFFIIDI',
      'GFFFHHIII',
      'GFHHHIIII',
      ],
      solution: [1, 6, 3, 8, 2, 4, 0, 5, 7],
      given: [],
    },
  ],
};

export function getLevel(difficulty: DifficultyId, index: number): Puzzle | null {
  return LEVELS[difficulty]?.[index] ?? null;
}

export function levelCount(difficulty: DifficultyId): number {
  return LEVELS[difficulty]?.length ?? 0;
}
