// 此檔由 scripts/build-levels.ts 自動產生，請勿手動編輯。
// 重新產生：npm run levels
//
// 每一關都經過求解器驗證，確認「恰好一組解」。
//   regions  — 每個字元代表一個彩色區域
//   solution — solution[row] = 該列柯基所在的欄
//
// 開局是空盤面，不預先放柯基。

import type { Puzzle } from './types.ts';

export const LEVELS: readonly Puzzle[] = [
  {
    level: 1,
    size: 5,
    regions: [
      'ABBBB',
      'BBBCC',
      'DDECC',
      'DDECC',
      'DDEEE',
    ],
    solution: [0, 2, 4, 1, 3],
  },
  {
    level: 2,
    size: 5,
    regions: [
      'BBBCA',
      'BBBCC',
      'DBBCC',
      'DEEEE',
      'DEEEE',
    ],
    solution: [4, 1, 3, 0, 2],
  },
  {
    level: 3,
    size: 5,
    regions: [
      'ACBBB',
      'CCBBB',
      'CCBBB',
      'EEEDD',
      'EEEDD',
    ],
    solution: [0, 3, 1, 4, 2],
  },
  {
    level: 4,
    size: 6,
    regions: [
      'BBAAAD',
      'BBAAAD',
      'BBCCCD',
      'BEECDD',
      'EEEEDD',
      'EEEDDF',
    ],
    solution: [3, 0, 2, 4, 1, 5],
  },
  {
    level: 5,
    size: 6,
    regions: [
      'AAAABB',
      'CCABBB',
      'CAABBB',
      'CEEEDD',
      'EEEEDD',
      'EEEDDF',
    ],
    solution: [1, 3, 0, 4, 2, 5],
  },
  {
    level: 6,
    size: 6,
    regions: [
      'AAAAAC',
      'BBAAAC',
      'BDDDCC',
      'BDDEEC',
      'BDDEEC',
      'BEEEEF',
    ],
    solution: [2, 0, 4, 1, 3, 5],
  },
  {
    level: 7,
    size: 6,
    regions: [
      'CBBAAA',
      'CCBBDD',
      'ECDDDD',
      'EEDDDD',
      'EEFFFF',
      'FFFFFF',
    ],
    solution: [5, 3, 1, 4, 0, 2],
  },
  {
    level: 8,
    size: 7,
    regions: [
      'EEBBAAC',
      'EEBBBCC',
      'EBBBDCC',
      'EEEFDCF',
      'EEEFFFF',
      'EGFFFFF',
      'EGGGGGF',
    ],
    solution: [5, 2, 6, 4, 0, 3, 1],
  },
  {
    level: 9,
    size: 7,
    regions: [
      'CCBBBAA',
      'CCCCBDD',
      'CCEDDDD',
      'CEEDDDD',
      'FEEDDDD',
      'FEGGGGG',
      'FEGGGGG',
    ],
    solution: [6, 4, 1, 5, 2, 0, 3],
  },
  {
    level: 10,
    size: 7,
    regions: [
      'DBBAAAC',
      'DDBBECC',
      'DDDEECC',
      'DDDEECE',
      'DDEEECE',
      'DDFEEEE',
      'GGFFEEE',
    ],
    solution: [5, 3, 6, 1, 4, 2, 0],
  },
  {
    level: 11,
    size: 7,
    regions: [
      'DBBBAAA',
      'DDBBBCA',
      'DDBBBCE',
      'DDFBBEE',
      'DFFFBEE',
      'DFFFGEE',
      'DFFGGEE',
    ],
    solution: [4, 2, 5, 0, 6, 1, 3],
  },
  {
    level: 12,
    size: 8,
    regions: [
      'BBBBBAAA',
      'BBBBBBAA',
      'EEBBBBCA',
      'DEFFFCCA',
      'DEEFCCAA',
      'DEEFFHHA',
      'GGEFFHHA',
      'GEEHHHHA',
    ],
    solution: [7, 3, 6, 0, 2, 4, 1, 5],
  },
  {
    level: 13,
    size: 8,
    regions: [
      'DAAAACCC',
      'DAABBCCC',
      'DDFFFCEG',
      'DFFFEEEG',
      'DFFFFEEG',
      'FFFGGGGG',
      'FFFHGGGG',
      'HHHHHHGG',
    ],
    solution: [1, 3, 5, 0, 6, 2, 7, 4],
  },
  {
    level: 14,
    size: 8,
    regions: [
      'BBBAAAAA',
      'CCBBDDAA',
      'CCBDDDDD',
      'FCBDDHHH',
      'FEEDDDDH',
      'FEDDGHHH',
      'FEGGGGHH',
      'EEGGHHHH',
    ],
    solution: [6, 3, 1, 4, 2, 0, 5, 7],
  },
  {
    level: 15,
    size: 8,
    regions: [
      'BBBBBBAA',
      'FDBBBBBC',
      'FDDDBEBC',
      'FFDEEEEE',
      'FFEEGEEE',
      'HFFGGEEE',
      'HHHHGGGG',
      'HHHHHGGG',
    ],
    solution: [6, 3, 7, 2, 5, 1, 4, 0],
  },
  {
    level: 16,
    size: 8,
    regions: [
      'BBBBBBAA',
      'BBBBBBBC',
      'BBBBCCBC',
      'BBDECCCC',
      'BFDEECCC',
      'FFDEGGGG',
      'FFDEEEEG',
      'FHHEEEGG',
    ],
    solution: [6, 3, 5, 2, 4, 0, 7, 1],
  },
  {
    level: 17,
    size: 9,
    regions: [
      'CCCDDAABB',
      'CCCDDEEBB',
      'CGGGDEEEE',
      'CCGDDEEEF',
      'GGGGDDEFF',
      'IIGGHHFFF',
      'IIGGHHHHH',
      'IIIHHHHHH',
      'IIIIHHHHH',
    ],
    solution: [5, 7, 0, 3, 6, 8, 2, 4, 1],
  },
  {
    level: 18,
    size: 10,
    regions: [
      'BBBBBAAAAA',
      'DBCCCCCCFF',
      'DBCCECCCCF',
      'DDCCEEEFFF',
      'GDGCCGEHHF',
      'GGGGGGEHFF',
      'GGGGGEEHII',
      'JGGGGEHHHI',
      'JGGGGEHIHI',
      'JJJHHHHIII',
    ],
    solution: [5, 1, 3, 0, 6, 8, 4, 7, 9, 2],
  },
  {
    level: 19,
    size: 10,
    regions: [
      'DAAAAABBBB',
      'DACCCBBEEE',
      'DDDCBBGEEE',
      'DFFGGGGEEE',
      'DFFGGEEEEJ',
      'FFGGGEHJJJ',
      'FGGGGEHJJJ',
      'FGGGIIHHJJ',
      'FFIIIIJJJJ',
      'IIIIIJJJJJ',
    ],
    solution: [2, 6, 3, 0, 8, 1, 4, 7, 5, 9],
  },
  {
    level: 20,
    size: 10,
    regions: [
      'BBBBBBBCAA',
      'BBBBBCCCCD',
      'BBBCCCCCCD',
      'BCCCCCCCCD',
      'GCFCCCEDDD',
      'GFFFFEEHHD',
      'GGIFFEEHHD',
      'GGIFFEHHHD',
      'JGIHHHHHHD',
      'JGGHHHHHHD',
    ],
    solution: [8, 3, 5, 9, 6, 4, 1, 7, 2, 0],
  },
  {
    level: 21,
    size: 10,
    regions: [
      'DDCCCCAABB',
      'DCCCCEEABB',
      'DDCCCEEAAB',
      'DCCCEEEAAB',
      'DDCCEEEFFG',
      'DDHHHEEFFG',
      'DDHHIEEEFG',
      'JJHJIIIIFI',
      'JJJJJIIIII',
      'JJJJJJIIII',
    ],
    solution: [6, 8, 3, 0, 4, 7, 9, 2, 5, 1],
  },
  {
    level: 22,
    size: 10,
    regions: [
      'EEEEEEAABB',
      'EEECCDDABB',
      'EECCCDDDBB',
      'ECCCDDDDHH',
      'EECFDFDHHH',
      'EGGFFFDHHH',
      'EGGGFFHHHH',
      'EEGGGGIIIH',
      'EEGGGIIIHH',
      'EGGGIIJJJJ',
    ],
    solution: [6, 8, 2, 4, 0, 3, 1, 9, 5, 7],
  },
  {
    level: 23,
    size: 10,
    regions: [
      'CCCBBBAAAA',
      'CCCCBBBBBE',
      'FCBBBBDDEE',
      'FCCBDDDDDE',
      'FFFHHHDDGE',
      'FHHHGGGGGG',
      'JHHHHIIIGG',
      'JJJHIIIIII',
      'JJJJJJJIII',
      'JJJJJJJJII',
    ],
    solution: [6, 4, 1, 5, 9, 0, 8, 3, 7, 2],
  },
  {
    level: 24,
    size: 10,
    regions: [
      'CAAABBBBBB',
      'CDDDBEBHHH',
      'CDDDDEEHHH',
      'CCDDDEEEHH',
      'CCCDDDGEHH',
      'CCFGDDGEHH',
      'CCFGGGGGHH',
      'JIIIIIIGHH',
      'JJIJJJIIHH',
      'JJJJJJJJJH',
    ],
    solution: [1, 4, 0, 3, 7, 2, 5, 9, 6, 8],
  },
  {
    level: 25,
    size: 10,
    regions: [
      'BAAAAAAAAA',
      'BBACCCDDDA',
      'BAABBCCDDD',
      'BBBBFCDDDD',
      'EGGBFDDDHH',
      'EGGFFFDDHH',
      'EGGGFFDDHH',
      'JIIIIFDDDH',
      'JJIIIHHHHH',
      'JJJIIIHHHH',
    ],
    solution: [7, 1, 6, 8, 0, 5, 3, 9, 4, 2],
  },
  {
    level: 26,
    size: 10,
    regions: [
      'EEEEEBCCCA',
      'EEEEBBBCCA',
      'EEEDDBBCCC',
      'EEEDDBBBCC',
      'EHHHDGGBBF',
      'EHHHDDGGFF',
      'HHHHHIGGIF',
      'HHJHHIIIIF',
      'JJJHHIIIIF',
      'JJJJJIIIII',
    ],
    solution: [9, 4, 7, 3, 0, 8, 6, 1, 5, 2],
  },
  {
    level: 27,
    size: 10,
    regions: [
      'CCCCBBBBAA',
      'DDCCCCEBBB',
      'DDFCCGEEEE',
      'DDFFGGGEEE',
      'DDFFGGGGEE',
      'IDFFFFGEEE',
      'IHHHHHGGGE',
      'IHJJHHHHHE',
      'IHJJHJJHJJ',
      'IHJJJJJJJJ',
    ],
    solution: [9, 7, 3, 1, 8, 2, 6, 4, 0, 5],
  },
  {
    level: 28,
    size: 10,
    regions: [
      'BBBBAADCCC',
      'BBBAADDCCC',
      'BBAAADDCDC',
      'BFAADDDDDC',
      'HFFDDGDDEE',
      'HFFFGGGEEE',
      'HFFFGGGGEE',
      'HHFIGGGGEE',
      'JHIIIGGGGE',
      'JIIIIIIGEE',
    ],
    solution: [5, 2, 9, 6, 8, 3, 7, 1, 4, 0],
  },
  {
    level: 29,
    size: 10,
    regions: [
      'BDDDCCCCAA',
      'BBDDDDCCCC',
      'BBBDDEECCC',
      'BDDDEEEFFF',
      'BDDEEEEEEF',
      'BDDEEEFEEF',
      'BBBGGEFFFF',
      'HBBHGGFFFF',
      'HHHHIGIFII',
      'JJJHIIIIII',
    ],
    solution: [8, 1, 7, 3, 5, 9, 4, 0, 6, 2],
  },
  {
    level: 30,
    size: 10,
    regions: [
      'AAAACCBBDD',
      'AAACCBBBDD',
      'AAACCCBBDD',
      'ACCCEEBBDF',
      'ACECEEEDDF',
      'EEEEEGFFFF',
      'EEEEGGFFFF',
      'HEGGGGFFIF',
      'HEEEGGFFII',
      'HHHGGGGJJJ',
    ],
    solution: [1, 5, 3, 8, 2, 6, 4, 0, 9, 7],
  },
];

export const LAST_LEVEL = LEVELS.length;

/** 關卡編號從 1 起算；超出範圍時回傳 null。 */
export function getLevel(level: number): Puzzle | null {
  return LEVELS[level - 1] ?? null;
}

/** 把關卡編號夾在有效範圍內，避免存檔指到不存在的關卡。 */
export function clampLevel(level: number): number {
  if (!Number.isFinite(level)) return 1;
  return Math.min(Math.max(Math.trunc(level), 1), LAST_LEVEL);
}
