// 此檔由 scripts/build-levels.ts 自動產生，請勿手動編輯。
// 重新產生：npm run levels
//
// 每一關都經過求解器驗證，確認「恰好一組解」。
//   regions  — 每個字元代表一個彩色區域
//   solution — solution[row] = 該列柯基所在的欄
//
// 開局是空盤面，不預先放柯基。

import type { Puzzle } from './types.ts';

export const LEVELS: readonly Puzzle[] = [
  {
    level: 1,
    size: 5,
    regions: [
      'ABBBB',
      'BBBCC',
      'DDECC',
      'DDECC',
      'DDEEE',
    ],
    solution: [0, 2, 4, 1, 3],
  },
  {
    level: 2,
    size: 5,
    regions: [
      'BBBCA',
      'BBBCC',
      'DBBCC',
      'DEEEE',
      'DEEEE',
    ],
    solution: [4, 1, 3, 0, 2],
  },
  {
    level: 3,
    size: 5,
    regions: [
      'ACBBB',
      'CCBBB',
      'CCBBB',
      'EEEDD',
      'EEEDD',
    ],
    solution: [0, 3, 1, 4, 2],
  },
  {
    level: 4,
    size: 6,
    regions: [
      'BBAAAD',
      'BBAAAD',
      'BBCCCD',
      'BEECDD',
      'EEEEDD',
      'EEEDDF',
    ],
    solution: [3, 0, 2, 4, 1, 5],
  },
  {
    level: 5,
    size: 6,
    regions: [
      'AAAABB',
      'CCABBB',
      'CAABBB',
      'CEEEDD',
      'EEEEDD',
      'EEEDDF',
    ],
    solution: [1, 3, 0, 4, 2, 5],
  },
  {
    level: 6,
    size: 6,
    regions: [
      'AAAAAC',
      'BBAAAC',
      'BDDDCC',
      'BDDEEC',
      'BDDEEC',
      'BEEEEF',
    ],
    solution: [2, 0, 4, 1, 3, 5],
  },
  {
    level: 7,
    size: 6,
    regions: [
      'CBBAAA',
      'CCBBDD',
      'ECDDDD',
      'EEDDDD',
      'EEFFFF',
      'FFFFFF',
    ],
    solution: [5, 3, 1, 4, 0, 2],
  },
  {
    level: 8,
    size: 7,
    regions: [
      'EEBBAAC',
      'EEBBBCC',
      'EBBBDCC',
      'EEEFDCF',
      'EEEFFFF',
      'EGFFFFF',
      'EGGGGGF',
    ],
    solution: [5, 2, 6, 4, 0, 3, 1],
  },
  {
    level: 9,
    size: 7,
    regions: [
      'CCBBBAA',
      'CCCCBDD',
      'CCEDDDD',
      'CEEDDDD',
      'FEEDDDD',
      'FEGGGGG',
      'FEGGGGG',
    ],
    solution: [6, 4, 1, 5, 2, 0, 3],
  },
  {
    level: 10,
    size: 7,
    regions: [
      'DBBAAAC',
      'DDBBECC',
      'DDDEECC',
      'DDDEECE',
      'DDEEECE',
      'DDFEEEE',
      'GGFFEEE',
    ],
    solution: [5, 3, 6, 1, 4, 2, 0],
  },
  {
    level: 11,
    size: 7,
    regions: [
      'DBBBAAA',
      'DDBBBCA',
      'DDBBBCE',
      'DDFBBEE',
      'DFFFBEE',
      'DFFFGEE',
      'DFFGGEE',
    ],
    solution: [4, 2, 5, 0, 6, 1, 3],
  },
  {
    level: 12,
    size: 8,
    regions: [
      'BBBBBAAA',
      'BBBBBBAA',
      'EEBBBBCA',
      'DEFFFCCA',
      'DEEFCCAA',
      'DEEFFHHA',
      'GGEFFHHA',
      'GEEHHHHA',
    ],
    solution: [7, 3, 6, 0, 2, 4, 1, 5],
  },
  {
    level: 13,
    size: 8,
    regions: [
      'DAAAACCC',
      'DAABBCCC',
      'DDFFFCEG',
      'DFFFEEEG',
      'DFFFFEEG',
      'FFFGGGGG',
      'FFFHGGGG',
      'HHHHHHGG',
    ],
    solution: [1, 3, 5, 0, 6, 2, 7, 4],
  },
  {
    level: 14,
    size: 8,
    regions: [
      'BBBAAAAA',
      'CCBBDDAA',
      'CCBDDDDD',
      'FCBDDHHH',
      'FEEDDDDH',
      'FEDDGHHH',
      'FEGGGGHH',
      'EEGGHHHH',
    ],
    solution: [6, 3, 1, 4, 2, 0, 5, 7],
  },
  {
    level: 15,
    size: 8,
    regions: [
      'BBBBBBAA',
      'FDBBBBBC',
      'FDDDBEBC',
      'FFDEEEEE',
      'FFEEGEEE',
      'HFFGGEEE',
      'HHHHGGGG',
      'HHHHHGGG',
    ],
    solution: [6, 3, 7, 2, 5, 1, 4, 0],
  },
  {
    level: 16,
    size: 8,
    regions: [
      'BBBBBBAA',
      'BBBBBBBC',
      'BBBBCCBC',
      'BBDECCCC',
      'BFDEECCC',
      'FFDEGGGG',
      'FFDEEEEG',
      'FHHEEEGG',
    ],
    solution: [6, 3, 5, 2, 4, 0, 7, 1],
  },
  {
    level: 17,
    size: 9,
    regions: [
      'CCCDDAABB',
      'CCCDDEEBB',
      'CGGGDEEEE',
      'CCGDDEEEF',
      'GGGGDDEFF',
      'IIGGHHFFF',
      'IIGGHHHHH',
      'IIIHHHHHH',
      'IIIIHHHHH',
    ],
    solution: [5, 7, 0, 3, 6, 8, 2, 4, 1],
  },
  {
    level: 18,
    size: 10,
    regions: [
      'BBBBBAAAAA',
      'DBCCCCCCFF',
      'DBCCECCCCF',
      'DDCCEEEFFF',
      'GDGCCGEHHF',
      'GGGGGGEHFF',
      'GGGGGEEHII',
      'JGGGGEHHHI',
      'JGGGGEHIHI',
      'JJJHHHHIII',
    ],
    solution: [5, 1, 3, 0, 6, 8, 4, 7, 9, 2],
  },
  {
    level: 19,
    size: 10,
    regions: [
      'DAAAAABBBB',
      'DACCCBBEEE',
      'DDDCBBGEEE',
      'DFFGGGGEEE',
      'DFFGGEEEEJ',
      'FFGGGEHJJJ',
      'FGGGGEHJJJ',
      'FGGGIIHHJJ',
      'FFIIIIJJJJ',
      'IIIIIJJJJJ',
    ],
    solution: [2, 6, 3, 0, 8, 1, 4, 7, 5, 9],
  },
  {
    level: 20,
    size: 10,
    regions: [
      'BBBBBBBCAA',
      'BBBBBCCCCD',
      'BBBCCCCCCD',
      'BCCCCCCCCD',
      'GCFCCCEDDD',
      'GFFFFEEHHD',
      'GGIFFEEHHD',
      'GGIFFEHHHD',
      'JGIHHHHHHD',
      'JGGHHHHHHD',
    ],
    solution: [8, 3, 5, 9, 6, 4, 1, 7, 2, 0],
  },
  {
    level: 21,
    size: 10,
    regions: [
      'DDCCCCAABB',
      'DCCCCEEABB',
      'DDCCCEEAAB',
      'DCCCEEEAAB',
      'DDCCEEEFFG',
      'DDHHHEEFFG',
      'DDHHIEEEFG',
      'JJHJIIIIFI',
      'JJJJJIIIII',
      'JJJJJJIIII',
    ],
    solution: [6, 8, 3, 0, 4, 7, 9, 2, 5, 1],
  },
  {
    level: 22,
    size: 10,
    regions: [
      'EEEEEEAABB',
      'EEECCDDABB',
      'EECCCDDDBB',
      'ECCCDDDDHH',
      'EECFDFDHHH',
      'EGGFFFDHHH',
      'EGGGFFHHHH',
      'EEGGGGIIIH',
      'EEGGGIIIHH',
      'EGGGIIJJJJ',
    ],
    solution: [6, 8, 2, 4, 0, 3, 1, 9, 5, 7],
  },
  {
    level: 23,
    size: 10,
    regions: [
      'CCCBBBAAAA',
      'CCCCBBBBBE',
      'FCBBBBDDEE',
      'FCCBDDDDDE',
      'FFFHHHDDGE',
      'FHHHGGGGGG',
      'JHHHHIIIGG',
      'JJJHIIIIII',
      'JJJJJJJIII',
      'JJJJJJJJII',
    ],
    solution: [6, 4, 1, 5, 9, 0, 8, 3, 7, 2],
  },
  {
    level: 24,
    size: 10,
    regions: [
      'CAAABBBBBB',
      'CDDDBEBHHH',
      'CDDDDEEHHH',
      'CCDDDEEEHH',
      'CCCDDDGEHH',
      'CCFGDDGEHH',
      'CCFGGGGGHH',
      'JIIIIIIGHH',
      'JJIJJJIIHH',
      'JJJJJJJJJH',
    ],
    solution: [1, 4, 0, 3, 7, 2, 5, 9, 6, 8],
  },
  {
    level: 25,
    size: 10,
    regions: [
      'BAAAAAAAAA',
      'BBACCCDDDA',
      'BAABBCCDDD',
      'BBBBFCDDDD',
      'EGGBFDDDHH',
      'EGGFFFDDHH',
      'EGGGFFDDHH',
      'JIIIIFDDDH',
      'JJIIIHHHHH',
      'JJJIIIHHHH',
    ],
    solution: [7, 1, 6, 8, 0, 5, 3, 9, 4, 2],
  },
  {
    level: 26,
    size: 10,
    regions: [
      'EEEEEBCCCA',
      'EEEEBBBCCA',
      'EEEDDBBCCC',
      'EEEDDBBBCC',
      'EHHHDGGBBF',
      'EHHHDDGGFF',
      'HHHHHIGGIF',
      'HHJHHIIIIF',
      'JJJHHIIIIF',
      'JJJJJIIIII',
    ],
    solution: [9, 4, 7, 3, 0, 8, 6, 1, 5, 2],
  },
  {
    level: 27,
    size: 10,
    regions: [
      'CCCCBBBBAA',
      'DDCCCCEBBB',
      'DDFCCGEEEE',
      'DDFFGGGEEE',
      'DDFFGGGGEE',
      'IDFFFFGEEE',
      'IHHHHHGGGE',
      'IHJJHHHHHE',
      'IHJJHJJHJJ',
      'IHJJJJJJJJ',
    ],
    solution: [9, 7, 3, 1, 8, 2, 6, 4, 0, 5],
  },
  {
    level: 28,
    size: 10,
    regions: [
      'BBBBAADCCC',
      'BBBAADDCCC',
      'BBAAADDCDC',
      'BFAADDDDDC',
      'HFFDDGDDEE',
      'HFFFGGGEEE',
      'HFFFGGGGEE',
      'HHFIGGGGEE',
      'JHIIIGGGGE',
      'JIIIIIIGEE',
    ],
    solution: [5, 2, 9, 6, 8, 3, 7, 1, 4, 0],
  },
  {
    level: 29,
    size: 10,
    regions: [
      'BDDDCCCCAA',
      'BBDDDDCCCC',
      'BBBDDEECCC',
      'BDDDEEEFFF',
      'BDDEEEEEEF',
      'BDDEEEFEEF',
      'BBBGGEFFFF',
      'HBBHGGFFFF',
      'HHHHIGIFII',
      'JJJHIIIIII',
    ],
    solution: [8, 1, 7, 3, 5, 9, 4, 0, 6, 2],
  },
  {
    level: 30,
    size: 10,
    regions: [
      'AAAACCBBDD',
      'AAACCBBBDD',
      'AAACCCBBDD',
      'ACCCEEBBDF',
      'ACECEEEDDF',
      'EEEEEGFFFF',
      'EEEEGGFFFF',
      'HEGGGGFFIF',
      'HEEEGGFFII',
      'HHHGGGGJJJ',
    ],
    solution: [1, 5, 3, 8, 2, 6, 4, 0, 9, 7],
  },
  {
    level: 31,
    size: 10,
    regions: [
      'ECCCAAABBB',
      'ECCAAGGDBD',
      'ECCFFGGDDD',
      'EEEFFGGGDD',
      'EFFFFGGGGG',
      'FFFFFGGGGG',
      'HFJFGGGIGG',
      'HHJFGIIIII',
      'HHJIIIIIII',
      'HHJJIIIIII',
    ],
    solution: [5, 8, 2, 9, 0, 4, 6, 1, 7, 3],
  },
  {
    level: 32,
    size: 10,
    regions: [
      'AAAAAAAAAC',
      'AAAAAAABBC',
      'AAAAAAAAAC',
      'ADDAECCCCC',
      'DDDEEGFFCF',
      'DDEEGGGFFF',
      'DDEGGGGGGF',
      'DHHHHGGIFF',
      'HHHHHIIIFF',
      'HHHHJJIIII',
    ],
    solution: [0, 7, 9, 1, 3, 8, 5, 2, 6, 4],
  },
  {
    level: 33,
    size: 10,
    regions: [
      'BBBBCAAAHH',
      'DBBBCCCAHH',
      'DBBCCCCAHH',
      'DCCCCAAAHH',
      'DCDDCEAFFH',
      'DCDDDEFFHH',
      'DDDIGGFHHH',
      'IDIIIGGHHH',
      'IDIIIJGJHH',
      'IIIIIJJJJH',
    ],
    solution: [6, 1, 3, 0, 5, 7, 4, 9, 2, 8],
  },
  {
    level: 34,
    size: 10,
    regions: [
      'CCCCCBBBAA',
      'CCCCBBBAAA',
      'CCCDDBBBBA',
      'CCDDDBEEEE',
      'CCCDDBFFFE',
      'CGCDDDFFFF',
      'GGGDDDHHFF',
      'GGGDIIJHHH',
      'GGGIIIJJJH',
      'IIIIIJJJJH',
    ],
    solution: [8, 4, 0, 2, 9, 6, 1, 7, 3, 5],
  },
  {
    level: 35,
    size: 10,
    regions: [
      'FFAAAABBBC',
      'FFADAAABGC',
      'FFADDDDDGC',
      'FEAADHHGGG',
      'FEEEHHHGGG',
      'FFHHHHHGGG',
      'IIHHHHHGGG',
      'IIIJJJHJJJ',
      'IIIIJJJJJJ',
      'IIIIIJJJJJ',
    ],
    solution: [3, 7, 9, 4, 2, 0, 8, 6, 1, 5],
  },
  {
    level: 36,
    size: 10,
    regions: [
      'DBBBBBBBAA',
      'DCCBBBBBBA',
      'DCCCCBAAAA',
      'DDCECAAAAF',
      'DDEECCAAAF',
      'EEECCCCCIF',
      'GHEEEECCIF',
      'GHHJJJJIII',
      'GHJJJIIIII',
      'GHJJJJIIII',
    ],
    solution: [8, 6, 4, 1, 3, 9, 0, 2, 7, 5],
  },
  {
    level: 37,
    size: 10,
    regions: [
      'EEECCBBBAA',
      'EECCCCDBDD',
      'EEFFCCDDDD',
      'EEFFFFFDDD',
      'EEFFFFFFFD',
      'HFFIFFFGGG',
      'HFFIIIGGGG',
      'HHHIIIIGGG',
      'HIIIJIJJJJ',
      'HIIIJJJJJJ',
    ],
    solution: [9, 7, 4, 8, 0, 2, 6, 1, 3, 5],
  },
  {
    level: 38,
    size: 10,
    regions: [
      'AAAAAAABBB',
      'AAAAAABBBB',
      'EEEAAACBBB',
      'EEEAACCCFD',
      'EEEECCCFFD',
      'EEEECCFFDD',
      'HGGEICFFFD',
      'HHJIICFFDD',
      'JHJIICIFFD',
      'JJJIIIIFDD',
    ],
    solution: [5, 8, 6, 9, 3, 7, 2, 0, 4, 1],
  },
  {
    level: 39,
    size: 10,
    regions: [
      'CCBBBBBAAA',
      'CCCCCBBDDA',
      'CCCCCBDDDE',
      'CCCCCBDDDE',
      'CCCCCFDDEE',
      'GCCFCFDDEE',
      'GGFFFFFDEE',
      'GGGGGGGDEH',
      'IGGJGJJJHH',
      'IJJJJJJJHH',
    ],
    solution: [7, 5, 2, 6, 8, 3, 1, 9, 0, 4],
  },
  {
    level: 40,
    size: 10,
    regions: [
      'DDBBBBBBAC',
      'DDDDBEECAC',
      'DDDBBEECCC',
      'DDDEBEEEEE',
      'DFDEEEEEGG',
      'DFDFFFEGGG',
      'FFFFFFGGGG',
      'FFFHFGGIGG',
      'FHHHFHHIIG',
      'FJJHHHHIII',
    ],
    solution: [8, 4, 9, 0, 5, 1, 6, 3, 7, 2],
  },
  {
    level: 41,
    size: 10,
    regions: [
      'AAAAAACCCC',
      'BBAAACCCCC',
      'DDAAAACCCC',
      'DDAEAECFFF',
      'DDDEEEEFFF',
      'DGDGGEIFFF',
      'DGDGEEIFFF',
      'GGGGGGIFHF',
      'GGGGGIIHHH',
      'IIIIIIJJHH',
    ],
    solution: [2, 0, 6, 1, 4, 9, 3, 8, 5, 7],
  },
  {
    level: 42,
    size: 10,
    regions: [
      'BBBBBBBAAD',
      'BBCCBBBBAD',
      'BBCBBBCBAD',
      'GBCCCCCCCD',
      'GBCCCECEEF',
      'GHHEEEEEFF',
      'GGHHEEEFFF',
      'IGHHEEEEFF',
      'IGJHHJEEFF',
      'IGJJJJFFFF',
    ],
    solution: [7, 4, 6, 9, 5, 8, 1, 3, 0, 2],
  },
  {
    level: 43,
    size: 10,
    regions: [
      'CCCBBBBBAA',
      'CCCCBBDBBD',
      'CCCEBDDDDD',
      'CCCEEDFDDD',
      'CCCEEDFFFD',
      'CCEEIFFFFF',
      'CGHEIFFFFF',
      'GGHHIIFFFF',
      'HHHHIIFFFF',
      'HJJIIIIIII',
    ],
    solution: [9, 7, 0, 8, 4, 6, 1, 3, 5, 2],
  },
  {
    level: 44,
    size: 10,
    regions: [
      'EEEEEECCAA',
      'EEDDCCCBBA',
      'EEDDDCCAAA',
      'EEDDEEEAAA',
      'EEEEEGGFFJ',
      'HHEGGGGJFJ',
      'HHHGIGGJJJ',
      'HHIIIJJJJJ',
      'HIIIIIIJJJ',
      'HIIIIIJJJJ',
    ],
    solution: [9, 7, 5, 2, 0, 8, 3, 1, 4, 6],
  },
  {
    level: 45,
    size: 10,
    regions: [
      'FFCCCBBAAA',
      'FFCCCCBBBD',
      'FFFFCCCDDD',
      'FFFEECDDDD',
      'FFFEEEEHDH',
      'FFGGGEHHDH',
      'GGGGGEJHHH',
      'IGIGGGJJJH',
      'IIIGIIJJJH',
      'IIIIIJJJJH',
    ],
    solution: [8, 6, 4, 7, 3, 0, 2, 9, 1, 5],
  },
  {
    level: 46,
    size: 10,
    regions: [
      'AAAAACCBBB',
      'AAACACCBBB',
      'AAACCCCDBB',
      'FFECCCCDBB',
      'FFEEECCDBB',
      'GFFEEEEDDH',
      'GFEEEJJDDH',
      'GGEEEJJJJH',
      'IIEJJJJJJJ',
      'JJJJJJJJJJ',
    ],
    solution: [3, 8, 5, 7, 4, 2, 0, 9, 1, 6],
  },
  {
    level: 47,
    size: 10,
    regions: [
      'BBBBBAAAAA',
      'BBBBBBBAAC',
      'BBBBBBCACC',
      'BBDBBBCCCE',
      'DDDDBBCCCE',
      'FFFFBHCEEE',
      'FGGFFHHHEE',
      'JJGFFHHHEE',
      'JJGIIHHHEE',
      'JJGIHHHHEE',
    ],
    solution: [7, 5, 8, 2, 9, 3, 1, 6, 4, 0],
  },
  {
    level: 48,
    size: 10,
    regions: [
      'CCCBBBBBAA',
      'CCCBDDDBBE',
      'GGCDDFDDEE',
      'GCCCDFDEEE',
      'GCCFFFFEEE',
      'GGGGFHHEHE',
      'GGGFFHHHHE',
      'GGGHHHHHHE',
      'JIIIHHHHHE',
      'JIIHHHHHHE',
    ],
    solution: [9, 7, 2, 6, 8, 4, 1, 5, 3, 0],
  },
  {
    level: 49,
    size: 10,
    regions: [
      'DDAAAABBBB',
      'DDDDCCBBBF',
      'DDCCCFFFFF',
      'DDCCFFFFFF',
      'DDECCFFFII',
      'EEEGCFFFII',
      'EEGGCFFFFI',
      'JGGCCHHIII',
      'JGGHHHIIII',
      'JJHHHHHHII',
    ],
    solution: [5, 8, 4, 0, 2, 7, 3, 6, 9, 1],
  },
  {
    level: 50,
    size: 10,
    regions: [
      'EEDDCCBBAA',
      'EEDDCCCBBG',
      'EEDCCCCFGG',
      'EEDCFFFFFG',
      'EEFFFFFGGG',
      'HFFFFIGGGG',
      'HFFFIIGGGG',
      'HHHFIIIGGG',
      'JJJIIIIIGG',
      'JJJJIIIIGG',
    ],
    solution: [9, 7, 5, 2, 0, 4, 8, 1, 6, 3],
  },
  {
    level: 51,
    size: 10,
    regions: [
      'CCBBBAAAAA',
      'CCCBBADEEE',
      'CBBBDDDEEE',
      'CCBBDDDDDE',
      'FCBBGDDEEE',
      'FFFFGDDDEE',
      'IFHHGGDDEE',
      'IFFHGJJDEE',
      'IIIHJJDDEE',
      'IHHHJJJEEE',
    ],
    solution: [8, 4, 0, 7, 9, 2, 5, 3, 1, 6],
  },
  {
    level: 52,
    size: 10,
    regions: [
      'BBBBBBDAAC',
      'BEFFFBDCCC',
      'EEFDDDDCDC',
      'EEFFFDDDDG',
      'EEFHHHHDGG',
      'EEFFHHHHGG',
      'EFFIIHHHGG',
      'IIIIIHJJJJ',
      'IIIJJJJJJJ',
      'IIIJJJJJJJ',
    ],
    solution: [7, 0, 9, 6, 1, 3, 8, 5, 2, 4],
  },
  {
    level: 53,
    size: 10,
    regions: [
      'BBBCCCCCAA',
      'BBBCBBBCAD',
      'BBBBBBCCDD',
      'BBFEEBECDH',
      'BBFEEEECHH',
      'BBFFEECCHH',
      'BGGFEEECHH',
      'GGIFEJEHHH',
      'GIIFJJJHHH',
      'GIJJJJJHHH',
    ],
    solution: [9, 0, 6, 8, 5, 3, 1, 7, 2, 4],
  },
  {
    level: 54,
    size: 10,
    regions: [
      'AAAAAABBBB',
      'ACCAAABBBB',
      'AACCAADEEB',
      'GGCCDDDDEE',
      'GCCCDDFEEE',
      'GGGGFFFEEE',
      'GGGHHHFEEE',
      'GGGGGHEEEE',
      'JIIGHHHHEE',
      'JIHHHHHHEE',
    ],
    solution: [4, 8, 3, 7, 9, 6, 1, 5, 2, 0],
  },
  {
    level: 55,
    size: 10,
    regions: [
      'CCCDBBBBAA',
      'CCCDDBEBFF',
      'CCCDDEEBFF',
      'GGDDEEEEFH',
      'GGGEEEEEFH',
      'GGGGGEEEFH',
      'GGGIIJEHHH',
      'GGIIIJEHHH',
      'GIIIIJEEHH',
      'IIIIIJJJHH',
    ],
    solution: [9, 5, 0, 2, 4, 8, 1, 7, 3, 6],
  },
  {
    level: 56,
    size: 10,
    regions: [
      'CCCABBBBBD',
      'CCCABBBBDD',
      'CCCCEEEDDD',
      'CCGCCEDDFF',
      'GCGEEEFFFF',
      'GGGGGFFFFH',
      'GGIIFFHHHH',
      'GGIIHHHHHH',
      'JGIIIHHHHH',
      'JIIIHHHHHH',
    ],
    solution: [3, 6, 2, 7, 5, 8, 1, 9, 4, 0],
  },
  {
    level: 57,
    size: 10,
    regions: [
      'CBBBBBBBAA',
      'CCBBBBDDDD',
      'CCCBBBBDDD',
      'CCCEFFFFFD',
      'EECEFGGGGG',
      'EEEEFFFFGG',
      'EEEFFIIGGG',
      'HJEEFIIIGG',
      'HJEIIIIIGG',
      'JJEEIIIIII',
    ],
    solution: [8, 4, 2, 9, 3, 5, 7, 0, 6, 1],
  },
  {
    level: 58,
    size: 10,
    regions: [
      'CCCCEBBBAA',
      'CCCEEDDBBB',
      'CCCEDDDDDF',
      'CCEEDDDDFF',
      'HCCEEEDFFF',
      'HHGGGGDFFF',
      'HIIGGGGGGF',
      'HHIIIIGGGF',
      'JHIIGGGIII',
      'JIIIIIIIII',
    ],
    solution: [9, 7, 2, 6, 4, 8, 5, 1, 3, 0],
  },
  {
    level: 59,
    size: 10,
    regions: [
      'DAACCCCCCB',
      'DDAACCCEEB',
      'DAAADCCEEE',
      'DDDDDDCCCE',
      'DDHHDDDFEE',
      'DDDHHHFFFE',
      'DDGGGHHIII',
      'GGGGHHHIII',
      'GGJJJJIIII',
      'GGJJJIIIII',
    ],
    solution: [1, 9, 5, 0, 8, 6, 2, 4, 7, 3],
  },
  {
    level: 60,
    size: 10,
    regions: [
      'CCCCCCCBAA',
      'CCFFCEEBBD',
      'CFFFFEEEDD',
      'CCFEEEEDDD',
      'CFFEEEEDGD',
      'FFFEEEEGGD',
      'FFFFEGEGDD',
      'HHIIGGGGGD',
      'HIIIJJGJJJ',
      'HHIIJJJJJJ',
    ],
    solution: [9, 7, 0, 8, 4, 2, 5, 1, 3, 6],
  },
  {
    level: 61,
    size: 10,
    regions: [
      'BAAAAAADCC',
      'BBAAAADDCC',
      'BBBAAADCCC',
      'BBBBADDDDF',
      'EBDDDDDDDF',
      'EEDDDDDDFF',
      'EEGDGGFFFF',
      'JEGGGGGFFH',
      'JJGGGGIIIH',
      'JJJGGGIIHH',
    ],
    solution: [3, 1, 7, 5, 0, 8, 4, 9, 6, 2],
  },
  {
    level: 62,
    size: 10,
    regions: [
      'FFBBBBBBAA',
      'FFFBBBBBAC',
      'FBBBEEDDDC',
      'FBBBBEEDDD',
      'FFFFFEEGGD',
      'FFFFFGGGGD',
      'FFFGGGGGGD',
      'HHGGGGIIII',
      'JJGGGGIIII',
      'JGGGIIIIII',
    ],
    solution: [8, 3, 9, 7, 5, 2, 4, 1, 6, 0],
  },
  {
    level: 63,
    size: 10,
    regions: [
      'GGCCCCCBDA',
      'GGCCCCBBDA',
      'GGFFCCDDDA',
      'GGFFCCDEDD',
      'GGFFFEEEDD',
      'GGFGFFEEHH',
      'GGGGIFFHHH',
      'GGIIIJJHHH',
      'GIIIJJHHHH',
      'IIJJJJHHHH',
    ],
    solution: [9, 6, 4, 8, 5, 2, 0, 7, 1, 3],
  },
  {
    level: 64,
    size: 10,
    regions: [
      'DDCCAAABBB',
      'DDDCAAAABB',
      'DDDCCGEEEE',
      'DDDDCGGGEE',
      'DDFDCGGEEE',
      'DDFFFGGGEE',
      'DDDFFGGGGH',
      'DFFFFFGGGH',
      'FFJJFIGHHH',
      'FJJIIIHHHH',
    ],
    solution: [4, 8, 3, 0, 7, 2, 6, 9, 5, 1],
  },
  {
    level: 65,
    size: 10,
    regions: [
      'GGGGBAAACC',
      'GGGBBBAACC',
      'GGGBBAAAAC',
      'GFBBDDDEEC',
      'GFFFFFFHEC',
      'GFFFFFFHHH',
      'GGGGFFFHHH',
      'IGFFFFFHHH',
      'IIIIFHHHHJ',
      'IIIIIHJJJJ',
    ],
    solution: [5, 3, 9, 4, 8, 2, 0, 7, 1, 6],
  },
  {
    level: 66,
    size: 10,
    regions: [
      'CCCCBBBAAD',
      'CCCCCBBBDD',
      'EEECCDDDDD',
      'EEEEFFFDHH',
      'EGGEFFFFHH',
      'EGGGIHFFHH',
      'GGJIIHHFHH',
      'GJJIHHHFHH',
      'GGJIIHHFFH',
      'JJJJHHHHHH',
    ],
    solution: [8, 5, 3, 7, 0, 6, 1, 9, 4, 2],
  },
  {
    level: 67,
    size: 10,
    regions: [
      'CCCCCCAABB',
      'CCCCCCCABD',
      'CCCCCCEDDD',
      'CCCCCCEFDD',
      'GGCCCEEFDF',
      'GGHHHHEFFF',
      'GGGHHHHHFF',
      'GIHHHHHHFF',
      'GIHHHHHJJJ',
      'IIIHJJJJJJ',
    ],
    solution: [6, 8, 2, 9, 5, 7, 0, 3, 1, 4],
  },
  {
    level: 68,
    size: 10,
    regions: [
      'CCCCAAAAAA',
      'CCCDADBBBA',
      'CCCDDDBEEE',
      'CFDDEEEEEH',
      'FFGGEEHHHH',
      'FFGGGEHHHH',
      'FGGGGHHHHH',
      'FIGGGJHHHH',
      'IIGIJJHHHH',
      'IIIIJJJHHH',
    ],
    solution: [9, 7, 0, 2, 5, 1, 4, 8, 3, 6],
  },
  {
    level: 69,
    size: 10,
    regions: [
      'BBBBBAAAAA',
      'BBBBBDACCC',
      'EBDBBDACCC',
      'EBDDDDDDCC',
      'EEEEDDDDCC',
      'EEFFDFCCCC',
      'GFFFFFCCCC',
      'GFFFFFHJII',
      'GFFFFFHJII',
      'GFFFFFJJII',
    ],
    solution: [5, 2, 8, 4, 1, 3, 0, 6, 9, 7],
  },
  {
    level: 70,
    size: 10,
    regions: [
      'BBBBBAAACC',
      'BBBBEEAADC',
      'BBEBEEADDC',
      'FFEEEEEDDD',
      'HFGEGEIIDD',
      'HFGGGEEIID',
      'HFGGGGGIIJ',
      'HHGGGGGGIJ',
      'HGGGGGIIIJ',
      'HHHHGGIIJJ',
    ],
    solution: [5, 2, 9, 7, 3, 1, 4, 0, 6, 8],
  },
  {
    level: 71,
    size: 10,
    regions: [
      'FFEEEEEAAA',
      'FFEECCCBBA',
      'FFEECCCCAA',
      'FFEEEDDDDD',
      'FEEEEGGDDD',
      'FFEEGGGDDD',
      'FFEGGGIDDD',
      'FFGGGIIHHH',
      'JFGJIIHHIH',
      'JJJJJIIIIH',
    ],
    solution: [9, 7, 4, 6, 2, 0, 3, 8, 5, 1],
  },
  {
    level: 72,
    size: 10,
    regions: [
      'CAAAAABBBB',
      'CCDDDDEBBG',
      'CCCCDDEEGG',
      'CCCDDFEEGG',
      'CCIIDFEEGG',
      'CCIIFFEEGG',
      'CIIIIFHEGG',
      'CIIIIFHJJJ',
      'CCIIIJJJJJ',
      'IIIIIJJJJJ',
    ],
    solution: [1, 8, 0, 3, 7, 4, 9, 6, 2, 5],
  },
  {
    level: 73,
    size: 10,
    regions: [
      'DDCCCAAABB',
      'DCCCCCAAEB',
      'DDDCFCCEEE',
      'DDDFFFGGGE',
      'DDDDDFGGEE',
      'DDDFFFFGGE',
      'DDDFFGGGGE',
      'DDHHFIIIGE',
      'DHHHHHIEEE',
      'DJJJHIIIEE',
    ],
    solution: [5, 9, 3, 0, 8, 4, 7, 2, 6, 1],
  },
  {
    level: 74,
    size: 10,
    regions: [
      'AAAAAAAAAA',
      'AAAAABBAAA',
      'AAAABBBCAC',
      'DDDDBBBCCC',
      'DDDEEGGGCC',
      'DFFFFFGGCC',
      'FFFHHFFGCC',
      'FJFFHGGGCC',
      'IJFJHHGGCC',
      'IJJJHGGGGC',
    ],
    solution: [8, 6, 9, 1, 3, 5, 7, 4, 0, 2],
  },
  {
    level: 75,
    size: 10,
    regions: [
      'BBBBBCCCAA',
      'BBBBCCCCCD',
      'BBBCCCCDDD',
      'FFEECCCDDG',
      'FFEEECCDGG',
      'HFFFECCDDG',
      'HHFIIIIIIG',
      'JHIIIIIIIG',
      'JHIIIIIIII',
      'JIIIIIIIII',
    ],
    solution: [8, 3, 5, 7, 4, 2, 9, 1, 6, 0],
  },
  {
    level: 76,
    size: 10,
    regions: [
      'BBBBBAAACC',
      'BBBBBBAAEC',
      'BBDFFBAEEC',
      'DBDFFFFHEE',
      'DDDFFFFHEE',
      'GGFFFFFHHE',
      'GGFGGFFHHE',
      'GGGGFFHHHJ',
      'IGGHHHHHHJ',
      'IIIIIIHJJJ',
    ],
    solution: [5, 3, 9, 2, 8, 4, 1, 6, 0, 7],
  },
  {
    level: 77,
    size: 10,
    regions: [
      'AAAACCCCBB',
      'DADDCCCCCB',
      'DDDDCCCECC',
      'DEEEEEEEGG',
      'HHEEEFFFGG',
      'HEEEFFFFFG',
      'HEEEFFFGGG',
      'HHEEEFFGJG',
      'HHIIJJJGJJ',
      'IIIIJJJJJJ',
    ],
    solution: [2, 9, 5, 0, 4, 6, 8, 1, 3, 7],
  },
  {
    level: 78,
    size: 10,
    regions: [
      'CCCCCBBAAA',
      'CCCEBBBDDD',
      'CEEEEDDDDD',
      'EEEEEEHHDF',
      'EEEEEEHHFF',
      'EEEEHEEHFF',
      'GGEIHHHHFF',
      'GEEIJJHHJJ',
      'GIEIIJJHJJ',
      'GIIIJJJJJJ',
    ],
    solution: [7, 4, 0, 8, 2, 9, 1, 6, 3, 5],
  },
  {
    level: 79,
    size: 10,
    regions: [
      'BBBBDAACCC',
      'BBBBDDAAAC',
      'BFBBDAAEEC',
      'FFFGDDDEEE',
      'FGGGGDHEHE',
      'FGIIGGHHHE',
      'FIIGGGGHHH',
      'FIIIGGHHHJ',
      'FFIIIIIJHJ',
      'FIIIIIIJJJ',
    ],
    solution: [5, 1, 9, 4, 7, 0, 3, 6, 2, 8],
  },
  {
    level: 80,
    size: 10,
    regions: [
      'AAACCBBBBB',
      'ACCCEBBBDD',
      'ACCCEBBFDD',
      'CCCEEFFFDD',
      'HCCCEEFFFD',
      'HIIIEEEFFD',
      'HIIJEGGFDD',
      'HIJJEGDDDD',
      'HIIJGGDDDD',
      'HIIJJGDDDD',
    ],
    solution: [1, 7, 3, 9, 5, 8, 6, 0, 2, 4],
  },
  {
    level: 81,
    size: 10,
    regions: [
      'CCCBBBBAAA',
      'CBBBEEEHHG',
      'CBBBEEEHHG',
      'DDDBEEEHGG',
      'DDDEEEHHGG',
      'FFDEEEEHGG',
      'FDDEHHHHGG',
      'FJJEHHHHIG',
      'FJJHHIHHIG',
      'FJJJJIIIII',
    ],
    solution: [7, 3, 0, 2, 5, 1, 9, 6, 8, 4],
  },
  {
    level: 82,
    size: 10,
    regions: [
      'CCBBBBBDAA',
      'CCBBBBBDDD',
      'CCCCBBBGDD',
      'EECCBGGGGD',
      'EEECBBGGGD',
      'FFEEHBGGGG',
      'HHHHHGGGGG',
      'HHHHHIIGIG',
      'HHHHHHIGII',
      'JJHHHIIIII',
    ],
    solution: [8, 5, 3, 9, 2, 0, 7, 4, 6, 1],
  },
  {
    level: 83,
    size: 10,
    regions: [
      'CCCAAABBBB',
      'CCCEEADDDB',
      'CFFEEADDDD',
      'FFFEEGGHDD',
      'FFEEIGHHHH',
      'FFEIIGHHHH',
      'FIIIIGHHHH',
      'IIIIIJJHHH',
      'IIIJJJJHJH',
      'IIIIIJJJJJ',
    ],
    solution: [4, 9, 0, 8, 3, 1, 5, 7, 2, 6],
  },
  {
    level: 84,
    size: 10,
    regions: [
      'FFFAAAAAAA',
      'FFFAAAACBB',
      'FFFDDDDCCC',
      'FGGGGDDEEE',
      'FFFGGDDEEE',
      'FFGGGDDJJE',
      'HFGGGIJJJE',
      'HFJGGIJJJE',
      'JJJIIIJJJJ',
      'JJJJJJJJJJ',
    ],
    solution: [6, 9, 7, 5, 8, 1, 3, 0, 4, 2],
  },
  {
    level: 85,
    size: 10,
    regions: [
      'CCBBBBAAAD',
      'CCEBEFADDD',
      'CCEEEFADDD',
      'CCCEFFDDDD',
      'CCEEFFDDDD',
      'GCEFFFFIID',
      'GEEHHHFIDD',
      'GGGHJHIIDD',
      'GJJJJIIIDD',
      'GJJJJIIIII',
    ],
    solution: [8, 3, 1, 9, 2, 6, 0, 5, 7, 4],
  },
  {
    level: 86,
    size: 10,
    regions: [
      'EAAAABBBCC',
      'EAAABBBCCC',
      'EDDBBBGCCC',
      'EDDGBBGFFC',
      'EDGGGGGFCC',
      'EIIGHGGFFF',
      'EEIHHHGGFF',
      'JEIHHHHFFF',
      'JEIIHHHHHF',
      'JJIIHHHHHF',
    ],
    solution: [4, 6, 8, 2, 0, 9, 7, 5, 3, 1],
  },
  {
    level: 87,
    size: 10,
    regions: [
      'FCCCCBBBAA',
      'FFFCCCBBBD',
      'FEEECCDDDD',
      'FEEEECCCDH',
      'FFFEEEHHHH',
      'FFGGGEHHHH',
      'FFGGGIHHHH',
      'JFFGIIHHHI',
      'JFJJJIIIHI',
      'JJJJJIIIII',
    ],
    solution: [9, 6, 4, 8, 3, 0, 2, 7, 5, 1],
  },
  {
    level: 88,
    size: 10,
    regions: [
      'DDDDAABBBB',
      'DDDDDABBBB',
      'DDDCCAAABB',
      'DDDDCCAABF',
      'DDECCAAFBF',
      'EDEEEGGFFF',
      'EEEEEGGFFH',
      'EEEEGGGFFH',
      'EEEJGGGIFH',
      'JJJJJIIIHH',
    ],
    solution: [4, 6, 3, 0, 2, 8, 5, 9, 7, 1],
  },
  {
    level: 89,
    size: 10,
    regions: [
      'AAAAAAAAAC',
      'AAABAAAAAC',
      'AABBAADDCC',
      'FBBBBADDDC',
      'FBBBBDDDDE',
      'FFHBDDDDGE',
      'FFHBBDGGGE',
      'FFHBHHGGGE',
      'IFHHHHGGEE',
      'IIIJJJJJJE',
    ],
    solution: [5, 3, 8, 6, 9, 1, 7, 2, 0, 4],
  },
  {
    level: 90,
    size: 10,
    regions: [
      'AAAADBBBBB',
      'CAADDBFFEE',
      'CAAADDFFFE',
      'CCCDDFFFFE',
      'GGDDFFFHHE',
      'GGDFFJFHHH',
      'GGGFFJFHHH',
      'IGGFFJJJHH',
      'IIFFFJJJJH',
      'IFFFFJJJJJ',
    ],
    solution: [3, 5, 0, 4, 9, 6, 2, 8, 1, 7],
  },
  {
    level: 91,
    size: 10,
    regions: [
      'DBBBBBAACC',
      'DDBBEEECCC',
      'DDDDEEECCF',
      'DEEEEEECFF',
      'GGGEFFFFFI',
      'GGGFFFFIII',
      'GGGGHHHIII',
      'GGJGHHIIII',
      'GJJJHHIIII',
      'GGJJJIIIII',
    ],
    solution: [7, 2, 8, 0, 3, 6, 1, 5, 9, 4],
  },
  {
    level: 92,
    size: 10,
    regions: [
      'FFBBBBBBAA',
      'FFDDBBDDCC',
      'FFFDDDDDCG',
      'FFFFDDEDDG',
      'FFFEEEEDGG',
      'FFFFEEEDGG',
      'HFEEEEEGGG',
      'HFEJJIIGGG',
      'HHHJIIIIGG',
      'JJJJIIIIGG',
    ],
    solution: [9, 4, 8, 5, 3, 1, 7, 0, 6, 2],
  },
  {
    level: 93,
    size: 10,
    regions: [
      'BBBBBAAADD',
      'FBBBBBCAAD',
      'FBBBBBCCCD',
      'FFBBBEECCD',
      'FFBBEEECCD',
      'FFFBBEECHJ',
      'GFFFFEEHHJ',
      'GGFEEEEHJJ',
      'IIEEIIEHHJ',
      'IIIIIIIJJJ',
    ],
    solution: [5, 3, 6, 9, 4, 2, 0, 7, 1, 8],
  },
  {
    level: 94,
    size: 10,
    regions: [
      'FFDDCBBBAA',
      'FDDDCCCBBE',
      'FFDDCCCEEE',
      'FFDDDDGEEE',
      'FFDGGGGGEE',
      'HFGGGGGGGI',
      'HFGGGGGIII',
      'HHGGGGIIII',
      'JJGGGIIIII',
      'JJJGGIIIII',
    ],
    solution: [9, 7, 5, 3, 8, 1, 4, 0, 6, 2],
  },
  {
    level: 95,
    size: 10,
    regions: [
      'AAAABBBBDD',
      'AABBBCCCDD',
      'AAFBFCCCDD',
      'EFFBFCDDDJ',
      'EEFFFCCCJJ',
      'GEFFCCHCHJ',
      'GFFFFFHCHJ',
      'IIIIIIHHHJ',
      'IIIIIIHJJJ',
      'IIIIIHHJJJ',
    ],
    solution: [2, 4, 6, 8, 1, 3, 0, 7, 5, 9],
  },
  {
    level: 96,
    size: 10,
    regions: [
      'AAAABBBBBB',
      'AAABBBCCCC',
      'FFAADBCCEE',
      'FFDDDBCEEE',
      'FHDGGGCEIE',
      'FHDGGGCEII',
      'FHJGGGGEII',
      'HHJGGGIIII',
      'HHJGGGIIII',
      'JJJGGGIIII',
    ],
    solution: [3, 5, 7, 4, 9, 0, 6, 1, 8, 2],
  },
  {
    level: 97,
    size: 10,
    regions: [
      'AAAAAABBCC',
      'AAAABABBBC',
      'AAAABABBCC',
      'FDADBBBCCC',
      'FDDDDBGCCE',
      'FFHHDBGCEE',
      'FHHDDGGGJE',
      'FHHDGGHGJJ',
      'IHHHHHHGJJ',
      'IIIIHHJJJJ',
    ],
    solution: [4, 6, 8, 3, 9, 1, 5, 2, 0, 7],
  },
  {
    level: 98,
    size: 10,
    regions: [
      'AAAACCCBBB',
      'AAACCCCBFF',
      'DAACCCCCFF',
      'DAAEEFFCCF',
      'DDAEEFFFFF',
      'GDIEFFHFFF',
      'GGIEEHHHHH',
      'IIIEJHHHHH',
      'IIIEJJJJHH',
      'IIEEEEEJJH',
    ],
    solution: [3, 7, 5, 0, 4, 9, 1, 6, 2, 8],
  },
  {
    level: 99,
    size: 10,
    regions: [
      'EEEEEAACDB',
      'EEEEECCCDB',
      'EEEFFFCCDD',
      'EEEFGCCDDD',
      'EEEFGGGGHD',
      'IFFFFGHHHD',
      'IFFFGGHHHH',
      'IIIFFJJHJH',
      'IIJFJJJJJH',
      'IIJJJJJJJH',
    ],
    solution: [5, 9, 6, 8, 0, 2, 4, 7, 1, 3],
  },
  {
    level: 100,
    size: 10,
    regions: [
      'EBBBCCCAAA',
      'EEBBBBCDDA',
      'EEEBGGCCDD',
      'EEEEGGGFFD',
      'EHEEGGGFFF',
      'HHEGGGGGFF',
      'HHIIGGGGJF',
      'HHIIIIIJJJ',
      'HIIIIIJJJJ',
      'HHIIJJJJJJ',
    ],
    solution: [7, 2, 6, 9, 0, 8, 4, 1, 3, 5],
  },
  {
    level: 101,
    size: 10,
    regions: [
      'BBBBBBAACC',
      'HHHBDBBECC',
      'HHHDDDDEEC',
      'HHDDDDDEEE',
      'HHHDDDDGEE',
      'HHFFGGGGEE',
      'HHIIIGGGGE',
      'HIIIIJJJGG',
      'JJIIJJJJJG',
      'JJJJJJJJJJ',
    ],
    solution: [7, 5, 9, 4, 8, 2, 6, 0, 3, 1],
  },
  {
    level: 102,
    size: 10,
    regions: [
      'BBBAAAACCC',
      'BBBDAAAAAC',
      'BBBDAEEECC',
      'BBDDDEEFFF',
      'BBBDDEEEGF',
      'BBJDEEGGGF',
      'BBJJHEGIII',
      'BBJJHHHIII',
      'BBJJHIIIII',
      'BJJJHIIIII',
    ],
    solution: [3, 0, 8, 2, 5, 9, 6, 4, 7, 1],
  },
  {
    level: 103,
    size: 10,
    regions: [
      'CCCCCAAABB',
      'CCCCDDDADB',
      'ECFFDDDDDG',
      'ECEFFFDGGG',
      'EEEFFDDGGG',
      'FFFFFIGGGG',
      'FFFFFIIGJJ',
      'FHHFFIGGGJ',
      'FHIIIIIJJJ',
      'HHHHJJJJJJ',
    ],
    solution: [5, 9, 1, 6, 0, 3, 7, 2, 4, 8],
  },
  {
    level: 104,
    size: 10,
    regions: [
      'AAAAAABCCC',
      'DDAAAABBCC',
      'DAAAAEECCC',
      'DDFFAEECCC',
      'DFFEEEECCG',
      'IFFFFEEGGG',
      'IIFFFFEGGG',
      'IIHHHEEGGG',
      'JIIIHEGGGG',
      'JIHHHGGGGG',
    ],
    solution: [5, 7, 9, 1, 6, 3, 8, 4, 2, 0],
  },
  {
    level: 105,
    size: 10,
    regions: [
      'BBBBBBBCAA',
      'DDBBEECCCC',
      'DDBEEEECCH',
      'DDBGEEEECH',
      'FDGGGEEECH',
      'FFFGGGGECH',
      'FFJJGGEECH',
      'FFFJGHHECH',
      'FIFJGGHHHH',
      'IIFJJHHHHH',
    ],
    solution: [8, 3, 7, 0, 6, 2, 5, 9, 1, 4],
  },
  {
    level: 106,
    size: 10,
    regions: [
      'BBBDDDAAAA',
      'BBFDDDACCC',
      'BFFDDDECEE',
      'BFFDDEEEEE',
      'FFFFFFHEEE',
      'FFFFFFHEGE',
      'FFFFFHHHGE',
      'FFFFHHJGGG',
      'IHHHHHJJGG',
      'IIIHHJJJJJ',
    ],
    solution: [6, 1, 7, 3, 9, 2, 8, 4, 0, 5],
  },
  {
    level: 107,
    size: 10,
    regions: [
      'BBBBBBBBAA',
      'EBBBBDCCCC',
      'EBBFBDCGGC',
      'EBFFDDCGCC',
      'EEFFDDDGCJ',
      'EHFFDGGGGJ',
      'HHHFDGGJJJ',
      'HHHFDGGGJJ',
      'IHHGGGJGJJ',
      'IHHGJJJJJJ',
    ],
    solution: [8, 4, 9, 5, 1, 3, 6, 2, 0, 7],
  },
  {
    level: 108,
    size: 10,
    regions: [
      'CCCCBBBDAA',
      'CCCCBEDDDD',
      'CCCCCEFFDJ',
      'CCCCCEFFDJ',
      'CCEEEEFFFJ',
      'GCEEEFFFJJ',
      'GEEEHFHHJJ',
      'IHHEHFHHJJ',
      'IIHHHHHHJJ',
      'IIHHHHHJJJ',
    ],
    solution: [9, 4, 2, 8, 3, 5, 0, 6, 1, 7],
  },
  {
    level: 109,
    size: 10,
    regions: [
      'EAABBBCCCC',
      'EDADBBBBBC',
      'EDDDBFBBBC',
      'EEDFFFFFBG',
      'EEFFHFFFBG',
      'EFFFHHHHHG',
      'EEIFFHHHGG',
      'EEIHHHHHHH',
      'EIIHIHHHJJ',
      'EIIIIJJJJJ',
    ],
    solution: [1, 5, 9, 2, 0, 3, 8, 6, 4, 7],
  },
  {
    level: 110,
    size: 10,
    regions: [
      'BBBBAAAACC',
      'BBDDDCCCCC',
      'FFFDDCCEEE',
      'FFFFDDCEEE',
      'FFFGGEEEHJ',
      'IFFGGHHHHJ',
      'IIFGGHHHJJ',
      'IIIGGHHHHJ',
      'IIIIHHHHJJ',
      'IIIIIHHHJJ',
    ],
    solution: [5, 0, 6, 4, 7, 1, 3, 8, 2, 9],
  },
  {
    level: 111,
    size: 10,
    regions: [
      'BBBBBBBAAA',
      'BDDBCCCCCA',
      'BDDDCCCCEE',
      'FDDDDDDCCE',
      'FDDDDDCCEE',
      'FFDFDCCEEE',
      'FFFFFCEEEG',
      'HFFIFFEJEG',
      'HFFIIIJJGG',
      'HIIIJJJJGG',
    ],
    solution: [7, 3, 5, 2, 8, 1, 9, 0, 4, 6],
  },
  {
    level: 112,
    size: 10,
    regions: [
      'AAAAABBBBF',
      'AAAAABBFBF',
      'AAACABBFFF',
      'DEECCCBBFF',
      'DEECGGHBBF',
      'EEGGGGHHHF',
      'IIGGGGGJHF',
      'IIIIGJJJHJ',
      'IIGGGJJJJJ',
      'IIJJJJJJJJ',
    ],
    solution: [4, 6, 3, 0, 2, 9, 5, 8, 1, 7],
  },
  {
    level: 113,
    size: 10,
    regions: [
      'BBBBBBBAAA',
      'BBBBBBAACA',
      'EBBBBBBBCA',
      'EEBFBDDDCA',
      'EEEFFFDDCC',
      'EEEFFDDDHC',
      'GGEFFFDDHC',
      'IGGGFHHHHC',
      'IJJJJJHHHH',
      'JJJJHHHHHH',
    ],
    solution: [9, 5, 8, 6, 2, 4, 1, 7, 0, 3],
  },
  {
    level: 114,
    size: 10,
    regions: [
      'DBBBBEECAA',
      'DBBBEEECCC',
      'DDDBEEECCC',
      'DDBBBEEECC',
      'DDDEEEEEEC',
      'FFDFFEEEEE',
      'FFFFGGEEEE',
      'FFFFGGGEGH',
      'IJJJGGGGGH',
      'IJJJJJJJHH',
    ],
    solution: [8, 2, 7, 1, 6, 3, 5, 9, 0, 4],
  },
  {
    level: 115,
    size: 10,
    regions: [
      'BBAAAAAACC',
      'BBBAAAACCC',
      'BBAAAAECCC',
      'DBBAAAECCC',
      'DDDFAEECEE',
      'DIIFAFEEEE',
      'GGIFFFFHHH',
      'GIIJJFFFFH',
      'GIIIJJJHHH',
      'GIIJJJJHHH',
    ],
    solution: [4, 2, 7, 0, 8, 5, 1, 9, 3, 6],
  },
  {
    level: 116,
    size: 10,
    regions: [
      'BBBCCCAAAE',
      'BBCCCCAEEE',
      'BDCCCGAEEE',
      'DDDGGGEEHH',
      'DDDGGEEEHH',
      'FFFFGEEEHH',
      'FFFFGGEEHH',
      'FFFGGGIEHH',
      'JFFFIIIHHH',
      'JFFIIIHHHH',
    ],
    solution: [8, 1, 4, 2, 7, 3, 5, 9, 6, 0],
  },
  {
    level: 117,
    size: 10,
    regions: [
      'BBBBBBBBAA',
      'BDBBBFFBCC',
      'BDDDDDFECE',
      'BBDFFFFEEE',
      'BDDFFFFEEE',
      'BBDFFFFFEE',
      'GGHHFFFFEE',
      'GGIHHHEEEJ',
      'GGIIJHEJJJ',
      'IIIIJJJJJJ',
    ],
    solution: [9, 0, 8, 2, 7, 4, 1, 5, 3, 6],
  },
  {
    level: 118,
    size: 10,
    regions: [
      'DDDAAAAAAB',
      'DAAAACBBBB',
      'DAAECCCBCB',
      'DDEECCCCCB',
      'HDEEEGGCBB',
      'HFFEGGJCBB',
      'HFIEGGJJBJ',
      'HIIGGJJBBJ',
      'HHIIGGJJJJ',
      'HIIGGGJJJJ',
    ],
    solution: [7, 9, 6, 1, 4, 2, 5, 0, 3, 8],
  },
  {
    level: 119,
    size: 10,
    regions: [
      'DBBBBBBAAA',
      'DDDDDDBBBC',
      'GGDDDEEEBC',
      'GGDDDFEEEE',
      'GGDHFFEEEE',
      'GGGHHFFFEE',
      'GGHHHIIFFE',
      'HHHHHIIFIE',
      'HHHHIIIIIE',
      'JJJIIIIIII',
    ],
    solution: [8, 6, 9, 3, 7, 5, 0, 2, 4, 1],
  },
  {
    level: 120,
    size: 10,
    regions: [
      'BBBBBBBAAC',
      'BBBBBBBACC',
      'DDBHBFBECE',
      'DGGHHFFEEE',
      'DGGHHFFEEE',
      'DGGHHFFFFF',
      'GGHHHHHFFJ',
      'GIIIJHJFJJ',
      'GIIJJHJJJJ',
      'GIIJJJJJJJ',
    ],
    solution: [7, 3, 8, 0, 9, 6, 1, 5, 2, 4],
  },
  {
    level: 121,
    size: 10,
    regions: [
      'CDDDDDBBAA',
      'CCCCCDBBEE',
      'IIICCDBEEE',
      'IGIICDDEEE',
      'IGGCCDDFEE',
      'IGGGFFFFEE',
      'IGGGGFHFFE',
      'IGIGJFHFHE',
      'IIIGJFHFHE',
      'IIJJJHHHHE',
    ],
    solution: [9, 7, 3, 5, 8, 4, 1, 6, 0, 2],
  },
  {
    level: 122,
    size: 10,
    regions: [
      'DDEEAAABBB',
      'DDDEACCCBB',
      'DDDEACCCBJ',
      'DDFEACCBBJ',
      'DFFEECCBBJ',
      'FFFEGGJJJJ',
      'IIFFGGJJJJ',
      'HIIFGGJJJJ',
      'HIIIGGJJJJ',
      'IIGGGJJJJJ',
    ],
    solution: [6, 9, 7, 1, 4, 2, 5, 0, 3, 8],
  },
  {
    level: 123,
    size: 10,
    regions: [
      'AAAAAACCCD',
      'BAAAAACCCD',
      'BBACCCCCCD',
      'BBBBBCCCDD',
      'BBEECCCDDD',
      'FFEEEEJJDD',
      'FEEEIJJJGG',
      'FFEEIJJHHH',
      'IIEEIIJJHH',
      'IIIIIJJJHH',
    ],
    solution: [2, 0, 5, 8, 3, 1, 9, 7, 4, 6],
  },
  {
    level: 124,
    size: 10,
    regions: [
      'DDCCCCBBAA',
      'DDCCCCBEEE',
      'DDDECCCEEH',
      'DFFEEEEEEH',
      'DFFFEEEHHH',
      'FFFFGGHHHH',
      'FFGGGGHHHH',
      'FIIIGJJJHJ',
      'FFIIGJJJJJ',
      'IIIJJJJJJJ',
    ],
    solution: [9, 6, 4, 0, 5, 1, 3, 8, 2, 7],
  },
  {
    level: 125,
    size: 10,
    regions: [
      'AAAAAAAAAB',
      'CCCAAAAABB',
      'CCCCAAAABB',
      'EECCCCDBBB',
      'EEEFDDDDBB',
      'EEEFFDDDBB',
      'GIEFFFHHHH',
      'GIFFJJJJJH',
      'IIFFFJJJJJ',
      'IFFFFJJJJJ',
    ],
    solution: [5, 8, 3, 6, 2, 4, 0, 9, 1, 7],
  },
  {
    level: 126,
    size: 10,
    regions: [
      'CCCCAAAAFB',
      'CCCCCAAAFB',
      'CCCCCCAFFF',
      'CCCCCDAAFF',
      'ECCGGDDDFF',
      'ECCGHHFFFF',
      'EGGGHHIIIJ',
      'EGGHHIIIJJ',
      'EEGGHHIIJJ',
      'EEEGHJJJJJ',
    ],
    solution: [4, 9, 2, 5, 0, 7, 1, 3, 6, 8],
  },
  {
    level: 127,
    size: 10,
    regions: [
      'BBBBBBBBAA',
      'BDBBBBEBBB',
      'DDBCCEEEBB',
      'DDDDGGGEEE',
      'FFFFFGGGEG',
      'HFHHGGGGGG',
      'HHHHGIIGGI',
      'JHHGGIIIII',
      'JHGGGIIIII',
      'JJJJJIIIII',
    ],
    solution: [9, 5, 3, 0, 8, 1, 7, 2, 6, 4],
  },
  {
    level: 128,
    size: 10,
    regions: [
      'AAAAABBBBB',
      'AAAADBBBGG',
      'CAAADBBBGG',
      'CCAADDDGGG',
      'FFAADDDEGG',
      'FFFFDDEEGG',
      'FFFFDJGGGG',
      'FHFFJJJGGG',
      'HHIIJJJJGG',
      'HHHIJJJJJG',
    ],
    solution: [4, 6, 0, 5, 7, 2, 9, 1, 3, 8],
  },
  {
    level: 129,
    size: 10,
    regions: [
      'AAACCCCBBB',
      'AAACDDCCBB',
      'AACCDDDDFF',
      'ACCGGGDFFF',
      'EECCGDDFFF',
      'ECCGGDGGGF',
      'CCCGGGGFFF',
      'HIIIGGJFFF',
      'HIIIIGJFJJ',
      'HIIIIGJJJJ',
    ],
    solution: [2, 8, 3, 6, 1, 9, 5, 0, 4, 7],
  },
  {
    level: 130,
    size: 10,
    regions: [
      'AAAAAAAAAE',
      'BBAAAAAAAE',
      'BBBBAACCEE',
      'DBFAAAGGGE',
      'DBFFFGGGEE',
      'DFFFFGGGHE',
      'DFFGGGGGHH',
      'FFFGGGHHHH',
      'JJGGGHHHHI',
      'JJJGHHHHHI',
    ],
    solution: [4, 1, 6, 0, 8, 3, 5, 7, 9, 2],
  },
  {
    level: 131,
    size: 10,
    regions: [
      'CCCBBBBBAA',
      'CCBBBDBBBA',
      'CCBBDDDDDA',
      'CCCCDDDDDA',
      'EEEFFDDGGG',
      'EFFFFDDDDG',
      'EJFFDDDDIG',
      'HJJFDFIDIG',
      'HJJFFFIIIG',
      'HJJJFIIIIG',
    ],
    solution: [8, 6, 1, 5, 2, 4, 9, 0, 7, 3],
  },
  {
    level: 132,
    size: 10,
    regions: [
      'DDDEEBAAAA',
      'DDDDEBBBAA',
      'DCCDEEBBBA',
      'DDDDEEHHHH',
      'FFFDEGHHHH',
      'FFGGGGHHHH',
      'FFFGIGIIHJ',
      'FJIIIIIJHJ',
      'FJIJIIJJJJ',
      'JJJJJJJJJJ',
    ],
    solution: [9, 6, 2, 0, 4, 1, 3, 8, 5, 7],
  },
  {
    level: 133,
    size: 10,
    regions: [
      'CCBBBBBAAA',
      'CCBBDDDDDD',
      'CCCFDDDJJJ',
      'CCFFDDDJJJ',
      'ECFFDDJJJJ',
      'EGFFFDIIJJ',
      'EGGHFHIIJJ',
      'EGHHHHIIJJ',
      'EGHHIIIIJJ',
      'GGHHHIIJJJ',
    ],
    solution: [8, 3, 1, 6, 0, 4, 2, 5, 7, 9],
  },
  {
    level: 134,
    size: 10,
    regions: [
      'BBAAAACCCC',
      'BDDAACCGGG',
      'BDDDDCCGGG',
      'BEEFDCGGGG',
      'EEEFFGGGGG',
      'EFFFGGGGGG',
      'IFFGGHHGGG',
      'IIFFFHHHHJ',
      'IIIJFJHHHJ',
      'IIIJJJJJJJ',
    ],
    solution: [5, 0, 6, 4, 1, 3, 9, 7, 2, 8],
  },
  {
    level: 135,
    size: 10,
    regions: [
      'HHBBBBBBAA',
      'HDDDDDBCCC',
      'HDDDDEECCE',
      'HHDDEEEEEE',
      'HHFDDGEEEE',
      'HHFDGGEIEE',
      'HHFGGGIIEE',
      'JHJGJGIIEE',
      'JHJGJIIIII',
      'JJJJJIIIII',
    ],
    solution: [9, 6, 8, 3, 7, 2, 4, 1, 5, 0],
  },
  {
    level: 136,
    size: 10,
    regions: [
      'CCCCAABBBB',
      'DDCCCBBBEE',
      'DCCCCBBEEE',
      'DCCFFFFEEE',
      'CCGFFFFEEI',
      'GGGGFHEEII',
      'GGGGGHEEII',
      'JGGHHHHIII',
      'JGGHHHIIII',
      'JJHHHHHIII',
    ],
    solution: [5, 7, 3, 0, 8, 4, 2, 6, 9, 1],
  },
  {
    level: 137,
    size: 10,
    regions: [
      'CCCAAABBBB',
      'CCCCAADBDB',
      'CEEEEEDDDD',
      'CEEEEEDDHD',
      'FFFFEGHHHH',
      'FFGGGGGGHH',
      'FFFFGGGGHH',
      'FIIIGJJJJH',
      'IIIIGJJJJJ',
      'IIIIJJJJJJ',
    ],
    solution: [3, 7, 0, 6, 4, 1, 5, 9, 2, 8],
  },
  {
    level: 138,
    size: 10,
    regions: [
      'AAAAABBBBB',
      'AAAACCBCBD',
      'AAAAACCCDD',
      'GAAACCCEDD',
      'GFFHHCCEDD',
      'GFFFHEEEDD',
      'GGFFHEEEED',
      'GIHHHHEEDD',
      'JIIHHHHEDD',
      'JIHHHHHEDD',
    ],
    solution: [4, 8, 6, 9, 7, 3, 1, 5, 2, 0],
  },
  {
    level: 139,
    size: 10,
    regions: [
      'EAAAAAAABB',
      'EECCCCCBBB',
      'EDDCCCCBGG',
      'EDDDFFFBGG',
      'EEEDFGGBGG',
      'EEEDFFGGGG',
      'EEEDFGGGGG',
      'EEHJFFFGGG',
      'IHHJFFFGGG',
      'IIIJJFGGGG',
    ],
    solution: [7, 9, 6, 3, 1, 5, 8, 2, 0, 4],
  },
  {
    level: 140,
    size: 10,
    regions: [
      'CCCCCCAAAB',
      'CCCCCCADAB',
      'GGCCCFDDDD',
      'GGCGFFEEDD',
      'GGGGGFEEED',
      'HGGFFFEEED',
      'HGGJJFIIID',
      'HGJJJIIIID',
      'JJJJJIIIID',
      'JJJJJJIIID',
    ],
    solution: [7, 9, 3, 8, 6, 4, 2, 0, 5, 1],
  },
  {
    level: 141,
    size: 10,
    regions: [
      'CCCBBBDAAD',
      'CCCBBDDDDD',
      'CCEEBDDHHH',
      'CEEEFDDHHH',
      'GEFFFFHHJH',
      'GGFGFHHHJJ',
      'GGGGGHHJJJ',
      'GGGGIHHHJJ',
      'GGGGIIHHJJ',
      'GGIIIJJJJJ',
    ],
    solution: [8, 3, 0, 6, 1, 4, 2, 7, 5, 9],
  },
  {
    level: 142,
    size: 10,
    regions: [
      'BBBBBBAAAF',
      'BEEEECCCCF',
      'BBEEECCFFF',
      'DDEDEEEFFF',
      'DDDDEFFFFF',
      'IIGGEHHFHH',
      'IIIGGHHHHH',
      'IIIJGJJHHJ',
      'IIIJJJJJJJ',
      'IIIIIJJJJJ',
    ],
    solution: [6, 0, 5, 1, 4, 7, 3, 8, 2, 9],
  },
  {
    level: 143,
    size: 10,
    regions: [
      'EAAADDBBBC',
      'EAADDDBBBC',
      'EAADDBBCCC',
      'EEADDDCCCC',
      'EEEFFDDCCC',
      'GGEFFFFHCC',
      'GIEJJFHHHC',
      'IIJJFFHHHC',
      'IIJJHHHHHH',
      'IIJJJHHHHH',
    ],
    solution: [3, 7, 9, 5, 2, 6, 0, 8, 1, 4],
  },
  {
    level: 144,
    size: 10,
    regions: [
      'CCCCCCAABB',
      'CEECCCDABD',
      'EEEECCDDDD',
      'EEEECCCGGD',
      'EEEEFFFGGG',
      'EHHHFGGGGG',
      'IIIHFGGGGG',
      'IIJHHGGJGJ',
      'IJJJHJJJJJ',
      'IJJJJJJJJJ',
    ],
    solution: [6, 8, 5, 9, 1, 4, 7, 3, 0, 2],
  },
  {
    level: 145,
    size: 10,
    regions: [
      'CCCCCBBAAA',
      'DCCCBBAAAE',
      'DCCCCBEEEE',
      'DCFCFHGEEE',
      'FFFFFHGGEG',
      'FFIFHHGGGG',
      'IIIHHHHGJJ',
      'IIHHJHHJJJ',
      'IIHJJJJJJJ',
      'IJJJJJJJJJ',
    ],
    solution: [9, 4, 2, 0, 8, 3, 7, 5, 1, 6],
  },
  {
    level: 146,
    size: 10,
    regions: [
      'DDDAACBBBB',
      'DAAACCCCBE',
      'DDAAACFCCE',
      'GDDDDDFECE',
      'GGDGGDFEEE',
      'GGGGIIFFHH',
      'JGIIIIIHHH',
      'JJIJJIIHHH',
      'JIIJJHHHHH',
      'JJJJJJJHHH',
    ],
    solution: [4, 8, 5, 3, 9, 6, 1, 7, 2, 0],
  },
  {
    level: 147,
    size: 10,
    regions: [
      'CCCDAABBBB',
      'CCCDDAFFBB',
      'CCDDDFFFEE',
      'CDDDDDFJEE',
      'GDDHDFFJJE',
      'GGGHHFJJJJ',
      'GIHHHHJJJJ',
      'GIHHHHHJJJ',
      'GIIHHHJJJJ',
      'GIIIHHJJJJ',
    ],
    solution: [4, 8, 1, 3, 9, 5, 0, 6, 2, 7],
  },
  {
    level: 148,
    size: 10,
    regions: [
      'BBBBCCAAAA',
      'BFFBBCCDDD',
      'FFBBBCCDDD',
      'FFFBEEEEDG',
      'FFFFEEEEEG',
      'FHHHHIEGGG',
      'FHHJJIIIGG',
      'HHJJJIIIGI',
      'HJJJJJJIII',
      'HJJJJJJJII',
    ],
    solution: [6, 3, 5, 8, 4, 0, 9, 1, 7, 2],
  },
  {
    level: 149,
    size: 10,
    regions: [
      'DBBBBAAACC',
      'DDBBBBACCC',
      'DDDDBAAEEC',
      'FFFDGGGEEE',
      'FFFDGGGEEE',
      'FFFFGGEEEE',
      'FFFFGGGGGE',
      'FHIIGGGEEE',
      'HHHIIGGGEE',
      'JJHIIIIGEE',
    ],
    solution: [7, 5, 9, 3, 8, 2, 6, 1, 4, 0],
  },
  {
    level: 150,
    size: 10,
    regions: [
      'BBBBAAAACC',
      'BBBBBAAAAC',
      'BBBBBAAACC',
      'BDBBFAGCCE',
      'DDFFFGGGCE',
      'DDDFFFGGGH',
      'DDFFFGGGHH',
      'DDFIIGGHHH',
      'DIIIIIJHHH',
      'IIIIIIJJJJ',
    ],
    solution: [4, 0, 8, 1, 9, 3, 5, 7, 2, 6],
  },
  {
    level: 151,
    size: 10,
    regions: [
      'BBBCCCDDAA',
      'BBCCCCDDDD',
      'BCCCDDDFDD',
      'BCCCCDFFDF',
      'BEEEEDFFFF',
      'BBEEHHHFFF',
      'GGGEHHHHFF',
      'GGEEEEHHHF',
      'IGGEEEHHHF',
      'IIJJJJHHHH',
    ],
    solution: [9, 1, 3, 8, 4, 7, 2, 6, 0, 5],
  },
  {
    level: 152,
    size: 10,
    regions: [
      'CCCCCBBBAA',
      'CCCCCCEBBB',
      'CCCCCEEEDD',
      'CCFCFFEDDD',
      'GCFCFEEEDD',
      'GCFFFFEDDD',
      'GGFFHHEJDD',
      'GGFFHHHJJJ',
      'IGFHHHHJJJ',
      'IGHHHHJJJJ',
    ],
    solution: [9, 7, 2, 8, 5, 3, 1, 4, 0, 6],
  },
  {
    level: 153,
    size: 10,
    regions: [
      'BBBBBBBCAA',
      'EBFFDDDCCC',
      'EEFFFDDDDC',
      'EFFFDDFDDH',
      'EEEFFFFDHH',
      'EFFFFFFDHH',
      'EIGFFGGGHJ',
      'EIGGGGGHHJ',
      'IIIGJGJHJJ',
      'IIIGJJJJJJ',
    ],
    solution: [8, 1, 9, 4, 0, 3, 5, 7, 2, 6],
  },
  {
    level: 154,
    size: 10,
    regions: [
      'CCCCCCCAAB',
      'CCCCCCCDDB',
      'EEECFFDDDD',
      'EEEEFFFFDD',
      'HHEEFFGGGD',
      'HHHEFGGGGI',
      'HHHEGGGGGI',
      'HJHEGIIGGI',
      'JJHHIIGGII',
      'JJJJIIIIII',
    ],
    solution: [7, 9, 3, 8, 2, 4, 6, 0, 5, 1],
  },
  {
    level: 155,
    size: 10,
    regions: [
      'GGBBCCCAAA',
      'GGBBBCCCEE',
      'GGDDDDCEEE',
      'GGGIDFFFEE',
      'GIIIIFFFEE',
      'GGIIIHFFEH',
      'GGIIHHHHHH',
      'GGIJHHHHHH',
      'GIIJHJHHHH',
      'GJJJJJJHHH',
    ],
    solution: [8, 2, 6, 4, 9, 7, 0, 5, 1, 3],
  },
  {
    level: 156,
    size: 10,
    regions: [
      'BBBBCCCCAA',
      'BBBBBCCCCC',
      'BBDDBDDCCC',
      'BBBDBDFFEE',
      'BBDDDDDFFE',
      'BBDGDDFFFE',
      'BBBGGFFFEE',
      'HIIGGFGFEE',
      'HIIIGGGFEE',
      'JJJIIIIFFE',
    ],
    solution: [8, 2, 7, 5, 9, 6, 4, 0, 3, 1],
  },
  {
    level: 157,
    size: 10,
    regions: [
      'AAAAAAAABB',
      'FAAAAAAABB',
      'FEEECCCDBB',
      'FEEECCCDDD',
      'FFEEECCDDD',
      'FFFEEECDDD',
      'FFGGEHCDDD',
      'IIIGHHDDDD',
      'IIIHHHHDDD',
      'JJIHHHHHDD',
    ],
    solution: [7, 9, 6, 8, 4, 1, 3, 5, 2, 0],
  },
  {
    level: 158,
    size: 10,
    regions: [
      'DDBBBBCAAC',
      'DDEBBCCCCC',
      'DDEBFFFFCF',
      'DEEBFFFFFF',
      'DDEEFFFFFI',
      'GDDEFFFHHI',
      'GGGEHHHHII',
      'JJJEHHIIII',
      'JHHHHIIIII',
      'JJHHHIIIII',
    ],
    solution: [7, 4, 8, 0, 3, 6, 2, 5, 9, 1],
  },
  {
    level: 159,
    size: 10,
    regions: [
      'CCCCBBBAAD',
      'CCCCCBBBDD',
      'CCCCCDDDDD',
      'CFGGGEEEDD',
      'FFFGEEDDDH',
      'FFGGGEHHHH',
      'IFJGGEJHHH',
      'IFJJJJJJHJ',
      'IJJJJJJJJJ',
      'JJJJJJJJJJ',
    ],
    solution: [7, 5, 2, 9, 4, 1, 3, 8, 0, 6],
  },
  {
    level: 160,
    size: 10,
    regions: [
      'BBBBDDDDAA',
      'BBDDDFFCCC',
      'BBDDDFFCCE',
      'GGDDFFFFFE',
      'GGDDFFFFFE',
      'GGDFFHFFFJ',
      'GGGFHHFJJJ',
      'GGGHHHHJJJ',
      'IHHHHHHJJJ',
      'IIIHHHJJJJ',
    ],
    solution: [8, 1, 7, 3, 9, 4, 2, 5, 0, 6],
  },
  {
    level: 161,
    size: 10,
    regions: [
      'BBBDAAAACC',
      'BBDDDEACCC',
      'DBDDEEECGC',
      'DDDDEECCGG',
      'DFDEEEECGG',
      'FFDFFEGGGG',
      'FFDDFEGGGG',
      'FFFFFEHGGG',
      'FIFHHHHJGG',
      'IIFHHJJJGG',
    ],
    solution: [4, 0, 9, 2, 5, 3, 8, 6, 1, 7],
  },
  {
    level: 162,
    size: 10,
    regions: [
      'EEEEEEEEEA',
      'EEEEBBBBBA',
      'EEEEEDFFCA',
      'EEEEEDFFCC',
      'EGGHFFFFFF',
      'GGHHHIFIFF',
      'GGHHHIIIIF',
      'GHHHHIIIII',
      'GHHHHIIIII',
      'JJJHHIIIII',
    ],
    solution: [9, 4, 8, 5, 0, 6, 1, 3, 7, 2],
  },
  {
    level: 163,
    size: 10,
    regions: [
      'AAACCBBBDD',
      'AAACCBBBDD',
      'CCCCCBBDDF',
      'CCCEEBFDFF',
      'GGGGEFFFFF',
      'GGGGJFFFHF',
      'IGIIJJJHHH',
      'IIIJJHHHHH',
      'IIJJJHHHHH',
      'IIJJJJHHHH',
    ],
    solution: [2, 6, 3, 7, 4, 9, 1, 8, 0, 5],
  },
  {
    level: 164,
    size: 10,
    regions: [
      'BBBBAAAADD',
      'BCBBBBAADD',
      'BCCCCAAADD',
      'BCCCCADDDD',
      'CCCCCEEDDD',
      'GGEEEEEEFF',
      'GGHHEEEIII',
      'GHHHEEEIII',
      'GGHHHHIIIJ',
      'GGHHHHHIIJ',
    ],
    solution: [4, 0, 2, 7, 5, 8, 1, 3, 6, 9],
  },
  {
    level: 165,
    size: 10,
    regions: [
      'CCAABBBDDD',
      'CCCBBEEDDD',
      'CCEEEEDDDD',
      'CCEEEDDFDF',
      'CEEEFFFFFF',
      'CCEEEHFFFF',
      'CCGGEHHIIF',
      'CCGHHHHIII',
      'CCJJHHHIII',
      'CJJJJJIIII',
    ],
    solution: [2, 4, 0, 8, 1, 7, 3, 6, 9, 5],
  },
  {
    level: 166,
    size: 10,
    regions: [
      'GGGGAAAABB',
      'GGGGACCCBD',
      'GFFFACECCD',
      'GGFFFFEEDD',
      'GGFFFFEDDH',
      'GGFGFHHHHH',
      'GGGGJJHHHH',
      'IIGGJJJHHH',
      'IIIJJHHHHH',
      'IJJJJJJJHH',
    ],
    solution: [4, 8, 5, 9, 6, 2, 0, 7, 1, 3],
  },
  {
    level: 167,
    size: 10,
    regions: [
      'CCCAAAABBB',
      'CCCCAFABBD',
      'CEEEAFFBBD',
      'IEEEGFFFDD',
      'IEEEGGHFFF',
      'IEIEGHHFHH',
      'IIIIGHHHHH',
      'IJJJHHHHHH',
      'IIJJJJHHHH',
      'IJJJJHHHHH',
    ],
    solution: [5, 8, 0, 9, 2, 7, 4, 6, 1, 3],
  },
  {
    level: 168,
    size: 10,
    regions: [
      'BBCCCDDDAA',
      'BBBCDDDDDD',
      'BCCCDDFFDF',
      'BBGDDDFDDF',
      'EEGGGGFFFF',
      'EHHHHGFIFI',
      'EHHHHGIIII',
      'HHJHIIIIII',
      'JJJHJIIIII',
      'JJJJJIIIII',
    ],
    solution: [9, 0, 2, 7, 1, 8, 5, 3, 6, 4],
  },
  {
    level: 169,
    size: 10,
    regions: [
      'DDBBBBBBAA',
      'DCCCBBBBBE',
      'DDCCCGGBEE',
      'DDFFCGGEEH',
      'DDFFGGEEEH',
      'DFFFFGGEEH',
      'FFFFIGGEEH',
      'FIIFIIGIIH',
      'FFIIIIIIJJ',
      'FIIIIIIJJJ',
    ],
    solution: [8, 4, 2, 0, 6, 1, 5, 9, 3, 7],
  },
  {
    level: 170,
    size: 10,
    regions: [
      'DDBBBAAACC',
      'DDDBBBAACC',
      'DDDBBBAAAC',
      'DDDDDBFFEC',
      'GDGGBBFFEE',
      'GDDGBBFFFE',
      'GGDGGHFFFE',
      'GGGGHHFFFJ',
      'IGHHHHHFFJ',
      'IIIIIHJJJJ',
    ],
    solution: [5, 3, 9, 2, 8, 6, 1, 4, 0, 7],
  },
  {
    level: 171,
    size: 10,
    regions: [
      'BBBAAAAACC',
      'BBDDDEEEEC',
      'BBDDDEEEEC',
      'BDDDEEGGEE',
      'BDFFFGGGEE',
      'BDHFHGGGGG',
      'HHHHHGGGGG',
      'HHHHHGGGGG',
      'IHHHGGGGGG',
      'IIHHHHGJJJ',
    ],
    solution: [5, 1, 9, 2, 8, 3, 6, 4, 0, 7],
  },
  {
    level: 172,
    size: 10,
    regions: [
      'DDDAAACBBB',
      'DDDDAACCCB',
      'DDDAACCCCC',
      'DDFFAAECCC',
      'DDFFFFEEEE',
      'HDHHFFFEEG',
      'HHHHFFFEGG',
      'JHJJJFIIIG',
      'JHJJJFFIIG',
      'JJJJJJFIIG',
    ],
    solution: [3, 9, 5, 0, 6, 4, 8, 1, 7, 2],
  },
  {
    level: 173,
    size: 10,
    regions: [
      'CAAAAAAAAB',
      'CCCCCCCAAB',
      'DDDFFFCFEE',
      'DDDFFFFFFE',
      'DDFFFFEEEE',
      'DDDDDFFFFE',
      'IGDHHFFEEE',
      'IGDDHFFEEE',
      'IJJJHHJEEE',
      'IIIJJJJEEE',
    ],
    solution: [7, 9, 6, 2, 8, 5, 1, 4, 0, 3],
  },
  {
    level: 174,
    size: 10,
    regions: [
      'BBAAAAADDE',
      'BBBAADADCE',
      'BBAADDDDCE',
      'BHDAADDDCE',
      'HHDDDDDFCE',
      'HHHIIDDFFF',
      'HIIIIGDGGF',
      'HHIIIGGGGF',
      'JIIIIIIGGF',
      'JIIIIIIGGG',
    ],
    solution: [4, 2, 8, 6, 9, 7, 5, 1, 3, 0],
  },
  {
    level: 175,
    size: 10,
    regions: [
      'CCBBBBBDAA',
      'CCCCBBBDDD',
      'CCCCBBBDDD',
      'CCCCBDBBDD',
      'CEEBBDDDDD',
      'EEEEBDFFFD',
      'EEEEFFFGGI',
      'EHJFFFIIII',
      'HHJJJJJIII',
      'HJJJJJJJII',
    ],
    solution: [9, 4, 0, 5, 2, 6, 8, 1, 7, 3],
  },
  {
    level: 176,
    size: 10,
    regions: [
      'CCCFFFAABB',
      'CCCFFDDAAB',
      'CFFFFDDDEE',
      'CCFFDDDDEE',
      'CHFFFFDDEE',
      'HHFFFFGGGG',
      'HHHFIIIGGG',
      'JJHIIIIIGG',
      'JJJIJIIIGG',
      'JJJJJJIIII',
    ],
    solution: [6, 9, 0, 4, 8, 3, 7, 2, 5, 1],
  },
  {
    level: 177,
    size: 10,
    regions: [
      'AAAAAAAABB',
      'HAAAAADBBB',
      'HHFFAADDCC',
      'HHFFAADDEE',
      'HFFAAAGDEE',
      'HFFAAAGDDE',
      'HFFAAGGGEE',
      'HHIGGGGGEE',
      'JHIIGGGGIE',
      'JHIIIIIIIE',
    ],
    solution: [4, 7, 9, 6, 8, 2, 5, 1, 3, 0],
  },
  {
    level: 178,
    size: 10,
    regions: [
      'AAAAACCCCB',
      'AAAACCCCBB',
      'AAFAAACCDB',
      'HFFFFACEDD',
      'HHFFGGGEEE',
      'HHHFGGGGEE',
      'JHGGGGGGEE',
      'JHIIIIIGGE',
      'JHIIIIIIEE',
      'JJIIIIIIEE',
    ],
    solution: [2, 8, 6, 9, 7, 3, 5, 1, 4, 0],
  },
  {
    level: 179,
    size: 10,
    regions: [
      'BBBBBCCCAA',
      'BEBBBCCCCC',
      'EEEBFFFCDD',
      'EEGBFFFFDD',
      'EGGFFFFFJJ',
      'GGGGGFFFJJ',
      'HHGGGJJJJJ',
      'HHGIIIIJJJ',
      'HIIIIIIIJJ',
      'HIIIIIJJJJ',
    ],
    solution: [8, 2, 7, 9, 0, 5, 3, 1, 4, 6],
  },
  {
    level: 180,
    size: 10,
    regions: [
      'CCCAAABBBB',
      'CCCCABBBEE',
      'CCDDABBEEE',
      'CCDDDBBEEE',
      'CFFDDBBEEE',
      'CFFFIIEEEG',
      'CFHFIIEGEG',
      'HHHFIIEGGG',
      'HJHFIIIGGG',
      'HJIIIIIIIG',
    ],
    solution: [5, 7, 0, 4, 8, 3, 9, 2, 6, 1],
  },
  {
    level: 181,
    size: 10,
    regions: [
      'CCCCCAAAAB',
      'ECCCCCCCCB',
      'EEECFCCCCC',
      'EEFFFCCCDD',
      'EFFFFCGGGG',
      'HHFFFGGGGG',
      'HHFHFFIGGG',
      'HHHHFIIGJJ',
      'HHHIIIIJJJ',
      'HHHIIIJJJJ',
    ],
    solution: [5, 9, 3, 8, 0, 2, 7, 1, 4, 6],
  },
  {
    level: 182,
    size: 10,
    regions: [
      'CAAAAADBBB',
      'CCCAADDBDB',
      'CCEAADDDDD',
      'CCEADDDDDD',
      'CCEEDDFFDD',
      'CCEEEDFFDF',
      'CCIIEGGFFF',
      'CHIIGGGGFF',
      'HHIIIGGGFF',
      'JJJIIIIGFF',
    ],
    solution: [5, 7, 0, 8, 3, 9, 6, 1, 4, 2],
  },
  {
    level: 183,
    size: 10,
    regions: [
      'BBBBBBBBAA',
      'CCCCBBBBDD',
      'EECCGBDDDD',
      'EECCGBDDDD',
      'EEECGDDDFF',
      'EECCGDDDDF',
      'EEEIGGDDFF',
      'HEEIGGFFFF',
      'HHIIIGGGFF',
      'JJIIIIIFFF',
    ],
    solution: [8, 6, 3, 7, 2, 9, 5, 0, 4, 1],
  },
  {
    level: 184,
    size: 10,
    regions: [
      'AAAAAAABBB',
      'AACACABBGG',
      'DCCCCAEEGG',
      'DDDCCEEEEG',
      'FDDDEEEEEG',
      'FFFFIEEGGG',
      'HFFIIEEGGG',
      'HHIIIIEGGG',
      'JHHHIIEGGI',
      'JHHHIIIIII',
    ],
    solution: [5, 7, 4, 2, 6, 3, 8, 1, 9, 0],
  },
  {
    level: 185,
    size: 10,
    regions: [
      'CCBBBBDDAA',
      'CCBBBDDDDD',
      'CCBBFDDDDD',
      'ECHHFDDJJJ',
      'EEEHFDDDJJ',
      'EEHHFFDJJJ',
      'EGHFFFDJJJ',
      'GGHHFFFIJJ',
      'GGHIFFIIJJ',
      'HHHIIIIJJJ',
    ],
    solution: [8, 4, 0, 6, 2, 5, 1, 3, 7, 9],
  },
  {
    level: 186,
    size: 10,
    regions: [
      'EEBBBBCCAA',
      'EEEEBBBCDD',
      'EEEEBBCCDF',
      'EEEEBGGFDF',
      'EEHGGGGFDF',
      'EEHHHGFFFF',
      'HHHHHGGGFF',
      'HHHHHHGGFF',
      'IHJJJJJFFF',
      'IHHJJJJJJF',
    ],
    solution: [9, 4, 6, 8, 1, 7, 5, 2, 0, 3],
  },
  {
    level: 187,
    size: 10,
    regions: [
      'CCCCCBBBAA',
      'CCCCCCFBBB',
      'CEEFFFFDDD',
      'CCEEFFFFDD',
      'EEEHHFFFGG',
      'EEHHFFGGGG',
      'IEEHFGGJGG',
      'IIIHHJJJGG',
      'IIIJHJJGGG',
      'IJJJJJJJJG',
    ],
    solution: [9, 7, 0, 8, 2, 4, 6, 3, 1, 5],
  },
  {
    level: 188,
    size: 10,
    regions: [
      'AAAABBBCCC',
      'AABBBBDDDC',
      'AAEEEFDDDC',
      'EEEEFFFDDD',
      'GGGEFFFFFJ',
      'GGGGFFHFJJ',
      'IGIGHHHJJJ',
      'IIIGHJHJJJ',
      'IHHGHJJJJJ',
      'HHHHHJJJJJ',
    ],
    solution: [2, 4, 9, 7, 3, 5, 1, 6, 0, 8],
  },
  {
    level: 189,
    size: 10,
    regions: [
      'AAABBCCCCC',
      'ABBBBCECCC',
      'DDDBBFEEEC',
      'DDDBBFFFEE',
      'DDDBFFFGEE',
      'DDDFFFFGGG',
      'DDDFFHGGGG',
      'DDDFHHGGGG',
      'DDDIHHHGGG',
      'IIIIIJJJJJ',
    ],
    solution: [0, 2, 9, 1, 8, 4, 7, 5, 3, 6],
  },
  {
    level: 190,
    size: 10,
    regions: [
      'CCCBBBBAAA',
      'CCCCDBBDAA',
      'CGCDDDDDEE',
      'GGGGFFDDEE',
      'GGGFFFHDHE',
      'GGGGFFHHHH',
      'IIGGIFFHHH',
      'IIIIIIJJHH',
      'IIIIJJJJJH',
      'IIIJJJJJHH',
    ],
    solution: [7, 5, 0, 6, 9, 4, 2, 8, 1, 3],
  },
  {
    level: 191,
    size: 10,
    regions: [
      'AAAAAAAACC',
      'AEEBBDDAAC',
      'EEFBDDDDDC',
      'EEFBDGGDDD',
      'EEFBDGGGGD',
      'FFFDDGGGJJ',
      'FFIGGGGJJJ',
      'HHIGGJGGGJ',
      'HIIIJJJJJJ',
      'HHIJJJJJJJ',
    ],
    solution: [6, 4, 9, 7, 0, 2, 5, 1, 3, 8],
  },
  {
    level: 192,
    size: 10,
    regions: [
      'DBBBBCCCAA',
      'DDBBBCCCCE',
      'FDDDCCEEEE',
      'FFDCCEEEEE',
      'HFFFCEEEGE',
      'HFFHGGGGGE',
      'HHHHIGGGEE',
      'HHHJIIGGGG',
      'HJJJIIIGGG',
      'HJJJJIIIGG',
    ],
    solution: [8, 3, 5, 2, 9, 1, 7, 0, 6, 4],
  },
  {
    level: 193,
    size: 10,
    regions: [
      'AADCCCCCEB',
      'ADDDCCEEEB',
      'DDDDCEEEEH',
      'DDDEEEEEHH',
      'DIDDFGEGHH',
      'DIFFFGGGHH',
      'IIGGGGHHHH',
      'IGGGGHHJHH',
      'IGGGJJHJHH',
      'IGGGJJJJJJ',
    ],
    solution: [1, 9, 4, 2, 6, 3, 5, 8, 0, 7],
  },
  {
    level: 194,
    size: 10,
    regions: [
      'AAAAAACCBB',
      'AAAAAACBBB',
      'AAAAACCBBE',
      'DADACCBBBE',
      'DDDCCCGBEE',
      'FDDDDGGEEE',
      'FDIGGGGEEH',
      'FFIGGGGGJH',
      'FFIIGGGJJH',
      'FFIIGGJJHH',
    ],
    solution: [1, 7, 5, 2, 8, 0, 4, 9, 3, 6],
  },
  {
    level: 195,
    size: 10,
    regions: [
      'EEEDDDDAAB',
      'EEEDDDDAAB',
      'EEDDDDCCCC',
      'EEEEDDDFCC',
      'EEEEHHDFCF',
      'EEEEHJDFFF',
      'GGHEHJJFFF',
      'GGHHHJJJFF',
      'IHHJHHJJJF',
      'IJJJJJJJJF',
    ],
    solution: [7, 9, 6, 4, 2, 8, 1, 3, 0, 5],
  },
  {
    level: 196,
    size: 10,
    regions: [
      'ECCCCBBBAA',
      'EEECCDDBBD',
      'FFECCDDDDD',
      'FFEEGGGDDD',
      'FFEEEGGDGD',
      'FFFEEEGGGJ',
      'IIFEEGGGGJ',
      'IIFEHHGJGJ',
      'IIIIJGGJJJ',
      'IIIJJJJJJJ',
    ],
    solution: [9, 7, 3, 8, 2, 0, 6, 4, 1, 5],
  },
  {
    level: 197,
    size: 10,
    regions: [
      'EECAAAABBB',
      'EECCCAADDB',
      'EEEECAADDD',
      'EEEECCHDDD',
      'EEFFFHHHHD',
      'FFFFFHHGHD',
      'IIIFFHHGDD',
      'IIIFFHJJJJ',
      'IIIIIHJJJJ',
      'IIIIIHJJJJ',
    ],
    solution: [3, 9, 4, 8, 0, 2, 7, 5, 1, 6],
  },
  {
    level: 198,
    size: 10,
    regions: [
      'BBBBAACCCD',
      'BBBBACCCDD',
      'EBAAACCCDD',
      'EBBBACCDDD',
      'EEFBAHIDDD',
      'EEFFHHIDDD',
      'GEFFFHIIDD',
      'GEGFFHHIDI',
      'GGGFFHHIII',
      'GGJJJHHIII',
    ],
    solution: [5, 2, 7, 9, 1, 3, 0, 6, 8, 4],
  },
  {
    level: 199,
    size: 10,
    regions: [
      'AAAAABBBBB',
      'AAAAABBBBB',
      'CCACACBDDD',
      'CCCCCCDDDD',
      'EECDDDDDDD',
      'GEEDDDDFDD',
      'GEEDDFFFFF',
      'GGIIIFFHHF',
      'GGIIIIIJJJ',
      'GGIIIIIJJJ',
    ],
    solution: [2, 5, 3, 6, 1, 7, 0, 8, 4, 9],
  },
  {
    level: 200,
    size: 10,
    regions: [
      'CCCCCAAAAB',
      'CCCCCCADBB',
      'CCCHCCDDEE',
      'FFFHCDDEEE',
      'FFFHCCCEEE',
      'FIFHHGEEJE',
      'FIFHHGEEJE',
      'IIHHHJJEJE',
      'IHHJJJJEJJ',
      'IIIIJJJJJJ',
    ],
    solution: [7, 9, 1, 6, 8, 2, 5, 3, 0, 4],
  },
];

export const LAST_LEVEL = LEVELS.length;

/** 關卡編號從 1 起算；超出範圍時回傳 null。 */
export function getLevel(level: number): Puzzle | null {
  return LEVELS[level - 1] ?? null;
}

/** 把關卡編號夾在有效範圍內，避免存檔指到不存在的關卡。 */
export function clampLevel(level: number): number {
  if (!Number.isFinite(level)) return 1;
  return Math.min(Math.max(Math.trunc(level), 1), LAST_LEVEL);
}
